<script>
/* Banco de exercícios — Anatomia e Histologia */

EX['anatomia/homeostase'] = {fontes:'histologia',
 internet:[
  {t:'me', f:ADAPT, e:'Os quatro tecidos fundamentais do corpo humano são:', a:['Ósseo, cartilaginoso, adiposo e sanguíneo','Epitelial, conjuntivo, muscular e nervoso','Epitelial, ósseo, muscular e adiposo','Conjuntivo, glandular, nervoso e linfático'],
   ok:1, d:'Todos os outros tecidos citados são subtipos de um desses quatro.', w:'São <b>epitelial, conjuntivo, muscular e nervoso</b>. Ósseo, cartilaginoso, adiposo e sanguíneo são todos <b>subtipos de tecido conjuntivo</b> — têm em comum a origem mesenquimal e a presença de matriz extracelular abundante. O tecido glandular é uma especialização do epitelial.'},
  {t:'me', f:ADAPT, e:'A principal característica que distingue o tecido epitelial do conjuntivo é:', a:['O epitelial tem pouca matriz extracelular e células justapostas; o conjuntivo tem matriz abundante','O epitelial é vascularizado e o conjuntivo não','O epitelial não possui membrana basal','O conjuntivo não tem células'],
   ok:0, d:'A pergunta é quanto espaço existe <i>entre</i> as células.', w:'O <b>epitélio</b> tem células <b>justapostas</b>, unidas por junções, com pouquíssima matriz — e é <b>avascular</b>, nutrindo-se por difusão a partir do conjuntivo subjacente através da <b>membrana basal</b>. O <b>conjuntivo</b> é o oposto: células dispersas em <b>matriz extracelular abundante</b> (fibras colágenas, elásticas e substância fundamental) e ricamente vascularizado.'},
  {t:'me', f:ADAPT, e:'A função de barreira seletiva do epitélio, essencial à homeostase, depende principalmente de:', a:['Da matriz extracelular','Das junções intercelulares, sobretudo das junções de oclusão (tight junctions)','Do tecido adiposo subjacente','Da inervação local'],
   ok:1, d:'O que impede uma molécula de simplesmente passar <i>entre</i> duas células vizinhas?', w:'As <b>junções de oclusão</b> selam o espaço paracelular, obrigando as substâncias a atravessar <i>através</i> das células — onde há transportadores e canais que selecionam o que entra. É isso que permite ao epitélio criar e manter compartimentos com composições diferentes, base de toda a homeostase. Desmossomos dão adesão mecânica e junções comunicantes (gap) permitem troca de íons entre células vizinhas.'}],
 ia:[
  {t:'me', e:'Por que o epitélio é avascular e como isso limita sua espessura?', a:['Porque não precisa de oxigênio','Porque se nutre por difusão a partir do conjuntivo subjacente, o que só funciona a poucas dezenas de micrômetros','Porque possui capilares próprios muito finos','Porque a membrana basal bloqueia o oxigênio'],
   ok:1, d:'Difusão só é eficiente em distâncias muito curtas — a mesma lógica da membrana alvéolo-capilar.', w:'Ter vasos no meio comprometeria a função de <b>barreira</b>, então o epitélio é avascular e recebe nutrientes por <b>difusão</b> a partir dos capilares do conjuntivo, atravessando a membrana basal. Como a difusão cai rapidamente com a distância, isso impõe um limite de espessura — e explica por que epitélios estratificados espessos, como a epiderme, têm camadas superficiais mortas e queratinizadas.'},
  {t:'me', e:'Uma glândula endócrina difere de uma exócrina, do ponto de vista embriológico e histológico, porque:', a:['A endócrina nunca deriva de epitélio','Durante o desenvolvimento, a endócrina perde a conexão com o epitélio de origem (perde o ducto) e passa a secretar para os capilares','A exócrina não tem células secretoras','A endócrina é sempre unicelular'],
   ok:1, d:'As duas nascem do mesmo lugar. O que acontece com o "cordão" que ligava a glândula à superfície?', w:'As duas nascem de uma <b>invaginação do epitélio</b> de revestimento. Na exócrina, o cordão de ligação persiste e vira o <b>ducto</b>. Na endócrina, esse cordão <b>degenera</b>: a glândula perde a conexão com a superfície e passa a lançar o produto no interstício, de onde vai para os capilares — que, por isso, são tipicamente <b>fenestrados</b> nos órgãos endócrinos.'},
  {t:'ab', e:'Explique como a organização dos tecidos permite ao organismo manter a homeostase, usando um exemplo de cada um dos quatro tecidos fundamentais.',
   d:'Para cada tecido, pergunte: ele separa, sustenta/transporta, move ou informa?',
   g:'<b>Epitelial — cria compartimentos.</b> Reveste superfícies e cavidades formando barreiras <b>seletivas</b>. As junções de oclusão impedem a passagem livre entre as células, obrigando o transporte a passar por transportadores específicos. É isso que permite manter o meio interno com composição diferente do meio externo. Exemplo: o epitélio tubular renal reabsorve seletivamente sódio, glicose e água, definindo a composição final da urina; o epitélio alveolar, finíssimo, permite a difusão dos gases.<br><br><b>Conjuntivo — sustenta, nutre e transporta.</b> Sua matriz extracelular preenche o espaço entre os epitélios e abriga os vasos que nutrem todo o resto. O <b>sangue</b>, um conjuntivo especializado, é o meio de transporte que leva O₂, nutrientes e hormônios e recolhe CO₂ e catabólitos — sem ele, nenhuma regulação de longa distância seria possível. O interstício também funciona como reservatório-tampão de líquido.<br><br><b>Muscular — executa.</b> É o efetor mecânico das alças homeostáticas. O músculo <b>cardíaco</b> gera o débito; o <b>liso</b> das arteríolas controla a resistência vascular e, portanto, a pressão arterial e a distribuição de fluxo; o <b>esquelético</b> produz calor nos calafrios e movimenta o corpo para longe da ameaça.<br><br><b>Nervoso — detecta, integra e comanda.</b> É o tecido dos sensores e do centro integrador. Osmorreceptores, termorreceptores, barorreceptores e quimiorreceptores convertem variáveis físicas e químicas em potenciais de ação; o hipotálamo e o tronco encefálico integram; e as vias eferentes autonômicas comandam os efetores em milissegundos.<br><br>A homeostase, portanto, não é função de um tecido, e sim da <b>integração</b> entre eles: o nervoso decide, o muscular executa, o conjuntivo transporta e o epitelial define os compartimentos onde tudo isso faz sentido.',
   c:[{p:'Epitelial: barreira seletiva e criação de compartimentos', k:['epitel','barreira','seletiv','junç','compartiment','reveste']},
      {p:'Conjuntivo: sustentação, matriz e transporte (sangue)', k:['conjuntiv','matriz','sangue','transporte','vaso','sustenta']},
      {p:'Muscular: efetor, contração de vasos ou coração', k:['muscul','contra','efetor','coração','liso','vaso']},
      {p:'Nervoso: sensor, integração e comando', k:['nervos','sensor','receptor','integra','comando','hipotálamo']},
      {p:'Explicou a integração entre os tecidos, não só a lista', k:['integra','junt','conjunto','coorden','atuam']}]}]};

EX['anatomia/sistema-cardiovascular'] = {fontes:'cardio',
 internet:[
  {t:'me', f:ADAPT, e:'A circulação pulmonar difere da sistêmica principalmente por:', a:['Transportar sangue arterial nas artérias','Ser um sistema de baixa pressão e baixa resistência','Não possuir capilares','Ser irrigada pelas artérias coronárias'],
   ok:1, d:'Compare 25/8 mmHg com 120/80 mmHg.', w:'A circulação pulmonar opera com pressões de ~<b>25/8 mmHg</b> (média ~15), contra 120/80 da sistêmica, porque sua resistência é muito menor. Isso é essencial: pressão alta nos capilares pulmonares causaria <b>edema pulmonar</b>. Repare também que ela inverte a regra do sangue: a <b>artéria</b> pulmonar leva sangue <i>venoso</i> e as <b>veias</b> pulmonares levam sangue <i>arterial</i>.'},
  {t:'me', f:ADAPT, e:'As artérias coronárias originam-se:', a:['Do arco aórtico','Dos seios aórticos, logo acima da valva aórtica','Do tronco pulmonar','Do átrio direito'],
   ok:1, d:'Elas são os primeiríssimos ramos da aorta — o coração se serve antes de servir aos outros.', w:'As coronárias direita e esquerda nascem dos <b>seios de Valsalva</b> (seios aórticos), logo acima das cúspides da valva aórtica. Detalhe fisiológico importante: o fluxo coronariano do ventrículo esquerdo acontece sobretudo na <b>diástole</b>, porque durante a sístole o próprio miocárdio contraído comprime os vasos intramurais. Por isso a taquicardia, que encurta a diástole, agrava a isquemia.'},
  {t:'me', f:ADAPT, e:'Qual vaso é o principal responsável pela resistência vascular periférica?', a:['A aorta','As arteríolas','Os capilares','As veias cavas'],
   ok:1, d:'Resistência varia com o raio elevado à quarta potência — e um desses vasos tem músculo liso para mudar o raio.', w:'As <b>arteríolas</b> são os vasos de resistência: têm túnica média muscular espessa em relação ao lúmen e forte inervação simpática, o que lhes permite variar o calibre. Pela lei de Poiseuille, a resistência é inversamente proporcional ao <b>raio elevado à quarta potência</b> — reduzir o raio pela metade multiplica a resistência por 16. É esse controle fino que distribui o débito entre os órgãos.'}],
 ia:[
  {t:'me', e:'Por que o ventrículo esquerdo tem parede muito mais espessa que o direito, se ambos ejetam o mesmo volume sistólico?', a:['Porque recebe mais sangue','Porque ejeta contra a resistência sistêmica (~80 mmHg), enquanto o direito ejeta contra a resistência pulmonar (~10 mmHg)','Porque tem mais valvas','Porque bate mais vezes por minuto'],
   ok:1, d:'O volume é o mesmo. O que muda é a pressão contra a qual cada um trabalha.', w:'Os dois ejetam o mesmo volume (é a lei de Frank-Starling que garante isso), mas contra <b>pós-cargas</b> muito diferentes: o esquerdo enfrenta a aorta a ~80 mmHg e o direito, o tronco pulmonar a ~10 mmHg. Como o trabalho de pressão é ~5–7 vezes maior à esquerda, a parede é proporcionalmente mais espessa. É também por isso que a hipertensão pulmonar crônica hipertrofia o ventrículo <i>direito</i> (cor pulmonale).'},
  {t:'me', e:'Uma pessoa tem estenose da valva aórtica. Qual adaptação do ventrículo esquerdo é esperada, e por quê?', a:['Dilatação (hipertrofia excêntrica), por sobrecarga de volume','Hipertrofia concêntrica, por sobrecarga de pressão','Atrofia da parede','Nenhuma adaptação'],
   ok:1, d:'A estenose é um obstáculo à saída. Isso é sobrecarga de pressão ou de volume?', w:'A estenose aórtica obriga o ventrículo a gerar pressões muito maiores para ejetar — <b>sobrecarga de pressão</b>. A resposta é a <b>hipertrofia concêntrica</b>: sarcômeros somados em paralelo, parede mais espessa, cavidade igual ou menor. O preço é a <b>disfunção diastólica</b> (ventrículo rígido, que enche mal — daí a B4) e o aumento da demanda de O₂ numa parede mais espessa. Sobrecarga de <b>volume</b> (insuficiência aórtica ou mitral) faz o oposto: hipertrofia <b>excêntrica</b>, com dilatação da cavidade.'},
  {t:'ab', e:'Descreva o trajeto completo de uma hemácia desde o átrio direito até retornar a ele, nomeando câmaras, valvas e grandes vasos.',
   d:'São duas voltas: primeiro a pequena circulação (pulmonar), depois a grande (sistêmica).',
   g:'<b>Átrio direito</b> → valva <b>tricúspide</b> → <b>ventrículo direito</b> → valva <b>pulmonar</b> (semilunar) → <b>tronco pulmonar</b> → artérias pulmonares direita e esquerda → arteríolas e <b>capilares alveolares</b>, onde ocorre a hematose: o sangue libera CO₂ e capta O₂, deixando de ser venoso e tornando-se arterial → vênulas → <b>veias pulmonares</b> (quatro, duas de cada pulmão) → <b>átrio esquerdo</b>.<br><br>Isso fecha a <b>circulação pulmonar (pequena circulação)</b>. Segue então:<br><br><b>Átrio esquerdo</b> → valva <b>mitral</b> (bicúspide) → <b>ventrículo esquerdo</b> → valva <b>aórtica</b> (semilunar) → <b>aorta</b> (ascendente, arco, descendente torácica e abdominal) → artérias de distribuição → arteríolas → <b>capilares sistêmicos</b>, onde entrega O₂ e nutrientes e recolhe CO₂ e catabólitos → vênulas → veias → <b>veia cava superior</b> (metade superior do corpo) e <b>veia cava inferior</b> (metade inferior), além do <b>seio coronário</b> (drenagem do próprio coração) → de volta ao <b>átrio direito</b>.<br><br>Isso fecha a <b>circulação sistêmica (grande circulação)</b>. Ponto importante: a artéria pulmonar é a única artéria que leva sangue venoso, e as veias pulmonares são as únicas veias que levam sangue arterial.',
   c:[{p:'Átrio direito → tricúspide → ventrículo direito', k:['tricúspide','átrio direito','ventrículo direito']},
      {p:'Valva pulmonar, tronco/artérias pulmonares e capilares alveolares', k:['pulmonar','tronco','alvéol','hematose','capilar']},
      {p:'Veias pulmonares → átrio esquerdo', k:['veias pulmonares','átrio esquerdo']},
      {p:'Mitral → ventrículo esquerdo → valva aórtica → aorta', k:['mitral','bicúspide','ventrículo esquerdo','aórtica','aorta']},
      {p:'Retorno pelas veias cavas ao átrio direito', k:['cava','superior','inferior','retorna']}]}]};

EX['anatomia/sistema-endocrino'] = {fontes:'endocrino',
 internet:[
  {t:'me', f:ADAPT, e:'A hipófise localiza-se em qual estrutura óssea?', a:['Forame magno','Sela túrcica do osso esfenoide','Seio frontal','Processo mastoide'],
   ok:1, d:'É uma "cadeira turca" escavada no osso que fica na base do crânio.', w:'A hipófise fica alojada na <b>sela túrcica</b> do <b>esfenoide</b>, ligada ao hipotálamo pela haste (infundíbulo). A relação anatômica tem consequência clínica direta: acima dela passa o <b>quiasma óptico</b>, e por isso tumores hipofisários que crescem para cima causam <b>hemianopsia bitemporal</b> — perda da visão periférica dos dois lados.'},
  {t:'me', f:ADAPT, e:'A tireoide relaciona-se anatomicamente com:', a:['A traqueia e a cartilagem cricoide, na região cervical anterior','O mediastino posterior','A cavidade abdominal','A fossa posterior do crânio'],
   ok:0, d:'É a glândula que sobe e desce quando você engole.', w:'A tireoide fica na <b>região cervical anterior</b>, com os lobos laterais à traqueia e o istmo cruzando-a à altura do 2º–4º anéis. Como está presa à laringe pela fáscia pré-traqueal, ela <b>sobe à deglutição</b> — manobra clássica do exame físico para diferenciar um nódulo tireoidiano de outras massas cervicais. Atrás dela ficam as <b>paratireoides</b> e o nervo laríngeo recorrente.'},
  {t:'me', f:ADAPT, e:'As zonas do córtex da suprarrenal e seus produtos são, de fora para dentro:', a:['Glomerulosa (mineralocorticoides), fasciculada (glicocorticoides), reticular (androgênios)','Fasciculada (aldosterona), glomerulosa (cortisol), reticular (adrenalina)','Reticular (aldosterona), fasciculada (androgênios), glomerulosa (cortisol)','Medular (cortisol) e cortical (adrenalina)'],
   ok:0, d:'Mnemônico: GFR — Sal, Açúcar, Sexo. "Quanto mais fundo, mais doce."', w:'De fora para dentro: <b>glomerulosa</b> → aldosterona (sal), <b>fasciculada</b> → cortisol (açúcar), <b>reticular</b> → androgênios (sexo). A <b>medula</b>, no centro, é de origem neural e produz <b>adrenalina e noradrenalina</b> — funcionalmente é um gânglio simpático modificado.'}],
 ia:[
  {t:'me', e:'Por que a adeno-hipófise depende do sistema porta-hipofisário, enquanto a neuro-hipófise não?', a:['Porque a adeno-hipófise não tem irrigação própria','Porque os fatores liberadores hipotalâmicos precisam chegar em alta concentração à adeno-hipófise por via sanguínea, enquanto ADH e ocitocina chegam à neuro-hipófise por transporte axonal','Porque a neuro-hipófise fabrica seus próprios hormônios','Porque o sistema porta drena a tireoide'],
   ok:1, d:'Uma metade recebe ordens pelo sangue; a outra recebe o próprio hormônio pronto, por dentro do axônio.', w:'O <b>sistema porta-hipofisário</b> é uma rede de capilares que leva os fatores liberadores (CRH, TRH, GnRH, GHRH) direto do hipotálamo à adeno-hipófise, em alta concentração e sem diluição sistêmica. A <b>neuro-hipófise</b> não precisa disso: ADH e ocitocina são <b>sintetizados nos corpos neuronais</b> dos núcleos supraóptico e paraventricular e descem por <b>transporte axonal</b> até serem liberados ali. Ela é, na prática, uma extensão do hipotálamo.'},
  {t:'me', e:'Um paciente apresenta hiperpigmentação da pele e das mucosas, hipotensão, fraqueza e hiponatremia. Qual a hipótese e por que a pele escurece?', a:['Síndrome de Cushing; o cortisol alto escurece a pele','Doença de Addison; o ACTH muito elevado compartilha precursor com o MSH e estimula os melanócitos','Hipotireoidismo; o TSH estimula melanócitos','Feocromocitoma; a adrenalina escurece a pele'],
   ok:1, d:'Se a adrenal falhou, o que acontece com o ACTH — e de qual proteína ele é derivado?', w:'Na <b>doença de Addison</b> (insuficiência adrenal <b>primária</b>) falta cortisol e aldosterona: hipotensão, fraqueza, hiponatremia e hipercalemia. Sem o feedback negativo, o ACTH dispara. Como ACTH e MSH derivam da mesma pró-proteína, a <b>pró-opiomelanocortina (POMC)</b>, o excesso estimula melanócitos e causa <b>hiperpigmentação</b> — típica em dobras cutâneas, cicatrizes e mucosa oral. É justamente esse sinal que separa a insuficiência primária da secundária, na qual o ACTH está baixo.'},
  {t:'ab', e:'Relacione a estrutura histológica de uma glândula endócrina com sua função, explicando por que os capilares desses órgãos costumam ser fenestrados.',
   d:'Se a glândula não tem ducto, por onde o hormônio sai? E o que a parede do vaso precisa ter para deixá-lo passar?',
   g:'A glândula endócrina é formada por <b>cordões ou folículos de células secretoras</b> apoiados em uma fina trama de conjuntivo reticular, sem ducto excretor. Como o produto não tem para onde escoar a não ser para o sangue, o parênquima é <b>intensamente vascularizado</b>, com os capilares em contato praticamente direto com as células.<br><br>Esses capilares são tipicamente <b>fenestrados</b>: seu endotélio possui poros (fenestras) de 60–80 nm fechados por um diafragma, o que aumenta muito a permeabilidade a moléculas hidrossolúveis de médio porte — exatamente o caso dos hormônios peptídicos e das catecolaminas, que não atravessariam com facilidade um endotélio contínuo. O resultado é a passagem rápida do hormônio recém-sintetizado para a circulação.<br><br>A forma de armazenamento também acompanha a função. As células que produzem hormônios <b>peptídicos</b> (hipófise, ilhotas pancreáticas) têm retículo endoplasmático rugoso e complexo de Golgi bem desenvolvidos e estocam o produto em <b>grânulos de secreção</b> prontos para exocitose imediata. As que produzem hormônios <b>esteroides</b> (córtex adrenal, gônadas) têm retículo <b>liso</b> abundante, mitocôndrias com cristas tubulares e gotículas de lipídio — não armazenam o hormônio pronto, sintetizam sob demanda a partir do colesterol. A <b>tireoide</b> é a exceção elegante: armazena o hormônio fora da célula, no <b>coloide</b> do folículo, o que lhe dá uma reserva para semanas.',
   c:[{p:'Glândula endócrina não tem ducto e secreta para o sangue', k:['sem ducto','ducto','sangue','capilar','interstício']},
      {p:'Capilares fenestrados aumentam a permeabilidade ao hormônio', k:['fenestrad','poro','permeab','fenestra']},
      {p:'Rica vascularização em contato próximo com as células secretoras', k:['vasculariz','irrigad','cordões','folículo','próximo']},
      {p:'Relacionou organelas ao tipo de hormônio (peptídico x esteroide)', k:['retículo','golgi','grânul','esteroid','peptíd','liso','rugoso','mitocôndria']}]}]};

EX['anatomia/sistema-nervoso-como-integrador-da-homeostase'] = {fontes:'nervoso',
 internet:[
  {t:'me', f:ADAPT, e:'A divisão simpática do sistema nervoso autônomo tem origem:', a:['Craniossacral','Toracolombar (T1 a L2)','Apenas no bulbo','Nos gânglios da base'],
   ok:1, d:'Uma divisão é toracolombar, a outra é craniossacral. Qual é a de "luta ou fuga"?', w:'O <b>simpático</b> é <b>toracolombar</b> (T1–L2), com gânglios próximos à medula (cadeia paravertebral), fibras pré-ganglionares curtas e pós-ganglionares longas — arranjo que favorece a <b>resposta difusa</b> de "luta ou fuga". O <b>parassimpático</b> é <b>craniossacral</b> (nervos III, VII, IX, X e S2–S4), com gânglios junto ao órgão-alvo e, portanto, ação mais <b>localizada</b>.'},
  {t:'me', f:ADAPT, e:'A estimulação parassimpática produz:', a:['Taquicardia, midríase e broncodilatação','Bradicardia, miose e aumento da motilidade digestiva','Vasoconstrição cutânea e sudorese','Aumento da glicogenólise hepática'],
   ok:1, d:'É o modo "repouso e digestão".', w:'O parassimpático é o sistema de <b>repouso e digestão</b>: reduz a FC (via vago sobre o nó sinusal), contrai a pupila (miose), broncoconstringe e aumenta a motilidade e a secreção digestivas. As demais alternativas descrevem respostas <b>simpáticas</b>. Vale notar que a inervação simpática das glândulas sudoríparas é uma exceção famosa: é simpática, mas <b>colinérgica</b>.'},
  {t:'me', f:ADAPT, e:'O hipotálamo participa da homeostase porque:', a:['É o centro da visão','Integra informações do meio interno e comanda respostas autonômicas, endócrinas e comportamentais','Produz apenas o líquor','Controla exclusivamente os movimentos voluntários'],
   ok:1, d:'Ele é a ponte entre o sistema nervoso e o endócrino.', w:'O hipotálamo é o <b>centro integrador</b> por excelência: recebe aferências de osmorreceptores, termorreceptores, barorreceptores e do estado nutricional, e responde por três vias — <b>autonômica</b> (simpático/parassimpático), <b>endócrina</b> (comandando a hipófise e produzindo ADH e ocitocina) e <b>comportamental</b> (sede, fome, busca de abrigo térmico).'}],
 ia:[
  {t:'me', e:'Por que uma lesão medular acima de T6 pode causar hipotensão grave e bradicardia (choque neurogênico)?', a:['Porque interrompe as vias motoras voluntárias','Porque interrompe a via simpática toracolombar, abolindo o tônus vasoconstritor e deixando o vago sem oposição','Porque lesa diretamente o nó sinusal','Porque causa hemorragia maciça'],
   ok:1, d:'Onde nasce o simpático? E se a via for cortada acima disso, quem sobra mandando no coração?', w:'Como o simpático sai da medula entre T1 e L2, uma lesão <b>acima</b> desse nível desconecta o centro vasomotor bulbar de todo o efluxo simpático: perde-se o <b>tônus vasoconstritor</b> e o leito vascular dilata (hipotensão por vasoplegia). Ao mesmo tempo, o vago — que chega pelo nervo craniano X, sem passar pela medula — continua íntegro e domina o coração, causando <b>bradicardia</b>. É a combinação que diferencia o choque neurogênico do hipovolêmico, no qual há taquicardia e extremidades frias.'},
  {t:'me', e:'A barreira hematoencefálica é seletivamente permeável ao CO₂ mas não ao H⁺ e ao HCO₃⁻. Qual a consequência fisiológica?', a:['O pH do líquor nunca muda','Os quimiorreceptores centrais respondem rapidamente à PaCO₂, mas com atraso a alterações metabólicas do pH sanguíneo','O CO₂ não afeta a ventilação','O H⁺ é o principal estímulo central direto'],
   ok:1, d:'O CO₂ entra e vira ácido carbônico do lado de dentro. E o H⁺ do sangue?', w:'O <b>CO₂</b> atravessa a barreira com facilidade, é hidratado no líquor e libera <b>H⁺ ali dentro</b> — é esse H⁺ local que os quimiorreceptores centrais realmente detectam. Já o H⁺ e o HCO₃⁻ do sangue <b>não atravessam</b>. Consequência: a resposta ventilatória à hipercapnia é <b>rápida e potente</b>, enquanto na acidose <b>metabólica</b> pura o estímulo inicial vem sobretudo dos quimiorreceptores <b>periféricos</b>, e a resposta central só se completa quando o bicarbonato do líquor se ajusta, o que leva horas.'},
  {t:'ab', e:'Compare o controle neural e o controle endócrino da homeostase quanto à velocidade, à duração, à especificidade do alvo e ao tipo de mensageiro.',
   d:'Pense num telefonema para uma pessoa específica versus um anúncio no rádio para a cidade inteira.',
   g:'<b>Velocidade.</b> O controle <b>neural</b> age em <b>milissegundos a segundos</b>: o potencial de ação percorre o axônio e a sinapse libera neurotransmissor a poucos nanômetros do receptor. O <b>endócrino</b> age em <b>minutos a horas</b>, porque o hormônio precisa ser secretado, transportado pelo sangue até o alvo e, no caso dos esteroides e tireoidianos, ainda desencadear transcrição gênica.<br><br><b>Duração.</b> A resposta neural é <b>breve</b> — o neurotransmissor é rapidamente recaptado ou degradado, e o efeito cessa quase junto com o estímulo. A endócrina é <b>prolongada</b>, durando enquanto o hormônio circular (ou enquanto persistirem as proteínas que ele mandou sintetizar), o que a torna adequada a processos lentos como crescimento, metabolismo e reprodução.<br><br><b>Especificidade do alvo.</b> O neural é <b>anatomicamente dirigido</b>: o axônio termina exatamente na célula que deve responder — é um endereço físico. O endócrino é <b>difuso</b>: o hormônio alcança todo o corpo pelo sangue, e a especificidade vem apenas da <b>presença do receptor</b> na célula-alvo. Por isso um mesmo hormônio pode ter efeitos diferentes em tecidos diferentes, conforme o receptor.<br><br><b>Mensageiro.</b> No neural, <b>neurotransmissores</b> liberados na fenda sináptica, em altíssima concentração local e por tempo muito curto. No endócrino, <b>hormônios</b> lançados na corrente sanguínea, em concentrações baixíssimas (nano a picomolares) e por tempo longo.<br><br><b>Integração.</b> Os dois não são independentes: o <b>hipotálamo</b> é a ponte, comandando a hipófise por via neural e hormonal; e a <b>medula da suprarrenal</b> é o exemplo mais direto — um gânglio simpático modificado que, em vez de fazer sinapse, despeja adrenalina no sangue, transformando um sinal neural em endócrino. Na prática, quase toda resposta homeostática combina os dois: o neural ganha tempo, o endócrino sustenta.',
   c:[{p:'Neural é rápido (ms a s) e endócrino é lento (min a h)', k:['rápid','milissegundo','segundos','lent','minutos','horas']},
      {p:'Neural tem efeito breve; endócrino, prolongado', k:['breve','curt','prolongad','duradour','sustenta']},
      {p:'Neural é anatomicamente dirigido; endócrino é difuso e depende do receptor', k:['dirigid','específic','difus','receptor','sangue','alvo']},
      {p:'Identificou neurotransmissor versus hormônio', k:['neurotransmissor','sinapse','hormôn','corrente sanguínea']},
      {p:'Citou a integração entre os dois (hipotálamo ou medula adrenal)', k:['hipotálamo','integra','suprarrenal','adrenal','ponte','junt']}]}]};

EX['anatomia/sistemas-respiratorio-renal-e-digestorio'] = {fontes:'respiratorio',
 internet:[
  {t:'me', f:ADAPT, e:'A porção condutora e a porção respiratória do sistema respiratório separam-se a partir de:', a:['Da traqueia','Dos bronquíolos respiratórios, onde surgem os primeiros alvéolos','Da laringe','Dos brônquios principais'],
   ok:1, d:'A fronteira é onde aparece o primeiro alvéolo na parede.', w:'A <b>porção condutora</b> (nariz, faringe, laringe, traqueia, brônquios e bronquíolos terminais) apenas conduz, aquece, umidifica e filtra o ar — é o <b>espaço morto anatômico</b> (~150 mL). A <b>porção respiratória</b> começa nos <b>bronquíolos respiratórios</b>, que já têm alvéolos brotando da parede, e segue por ductos alveolares, sacos alveolares e alvéolos.'},
  {t:'me', f:ADAPT, e:'A unidade funcional do rim é:', a:['O glomérulo isoladamente','O néfron','O cálice renal','A pirâmide medular'],
   ok:1, d:'A unidade precisa dar conta de filtrar, reabsorver e secretar — não só de filtrar.', w:'O <b>néfron</b> é a unidade funcional: corpúsculo renal (glomérulo + cápsula de Bowman), túbulo contorcido proximal, alça de Henle, túbulo contorcido distal e ducto coletor. Cada rim tem cerca de <b>1 milhão</b> deles. O glomérulo sozinho só filtra; a função renal completa exige também reabsorver, secretar e concentrar.'},
  {t:'me', f:ADAPT, e:'A maior parte da absorção de nutrientes ocorre em qual segmento?', a:['Estômago','Intestino delgado, sobretudo no jejuno','Intestino grosso','Esôfago'],
   ok:1, d:'Onde estão as vilosidades e microvilosidades?', w:'O <b>intestino delgado</b> é o órgão da absorção, e o <b>jejuno</b> é o principal segmento. Sua superfície é amplificada em três níveis — pregas circulares (válvulas coniventes), <b>vilosidades</b> e <b>microvilosidades</b> (a borda em escova) —, chegando a ~200 m². O <b>íleo</b> tem funções específicas: vitamina B12 (com fator intrínseco) e sais biliares. O intestino grosso absorve sobretudo <b>água e eletrólitos</b>.'}],
 ia:[
  {t:'me', e:'Por que a barreira de filtração glomerular impede a passagem de albumina, mesmo ela sendo menor que os poros do endotélio?', a:['Porque a albumina é grande demais para qualquer poro','Porque a barreira seleciona por tamanho E por carga: a membrana basal e os podócitos têm carga negativa que repele a albumina, também negativa','Porque a albumina é reabsorvida integralmente no túbulo','Porque a albumina não circula no plasma'],
   ok:1, d:'Existem dois filtros sobrepostos. Um é físico; o outro é elétrico.', w:'A barreira tem três camadas — endotélio fenestrado, membrana basal glomerular e os pedicelos dos podócitos com seus diafragmas de fenda — e filtra por <b>tamanho</b> e por <b>carga</b>. A membrana basal é rica em <b>proteoglicanos com carga negativa</b> (heparan-sulfato) que repelem a albumina, igualmente aniônica. Por isso doenças que neutralizam essa carga, como a <b>doença de lesões mínimas</b>, causam proteinúria maciça sem qualquer alteração visível à microscopia óptica.'},
  {t:'me', e:'Qual característica histológica do epitélio respiratório explica sua função de defesa?', a:['Ser pavimentoso estratificado queratinizado','Ser pseudoestratificado cilíndrico ciliado com células caliciformes — o aparelho mucociliar','Ser cúbico simples sem cílios','Não possuir membrana basal'],
   ok:1, d:'Muco para prender a sujeira, cílios para varrer.', w:'O <b>epitélio respiratório</b> é pseudoestratificado cilíndrico <b>ciliado</b> com <b>células caliciformes</b>. As caliciformes produzem o muco que aprisiona partículas e microrganismos; os cílios batem coordenadamente em direção à faringe, formando o <b>aparelho mucociliar</b>, que remove esse muco para ser deglutido ou expelido. O tabagismo paralisa e destrói os cílios — daí a tosse produtiva crônica e a maior propensão a infecções.'},
  {t:'ab', e:'Explique como os sistemas respiratório, renal e digestório se integram na manutenção do equilíbrio ácido-base e hidroeletrolítico.',
   d:'Um regula o CO₂, outro regula o bicarbonato e os íons, e o terceiro é a porta de entrada e uma via de perda.',
   g:'<b>Respiratório — o componente volátil.</b> Controla a <b>PaCO₂</b>, que é o denominador da equação de Henderson-Hasselbalch. Ao ajustar a ventilação alveolar em <b>minutos</b>, elimina o ácido volátil (H₂CO₃/CO₂) produzido pelo metabolismo — cerca de 15.000 mmol por dia. É a compensação rápida de qualquer distúrbio metabólico: hiperventila na acidose (Kussmaul), hipoventila na alcalose. Mas nunca normaliza o pH sozinho, apenas o aproxima.<br><br><b>Renal — o componente fixo e definitivo.</b> Controla o <b>HCO₃⁻</b>, o numerador da equação. Reabsorve praticamente todo o bicarbonato filtrado no túbulo proximal, e <b>excreta</b> os ácidos fixos (~70 mmol/dia) como acidez titulável (tamponada por fosfato) e sobretudo como <b>NH₄⁺</b>, cuja produção pode aumentar várias vezes na acidose crônica. É lento (horas a dias), mas é o único que realmente elimina ácido e <i>regenera</i> base. O rim também é o guardião final do <b>Na⁺, K⁺, Cl⁻ e da água</b>, sob comando de aldosterona e ADH, definindo volume e osmolaridade do LEC.<br><br><b>Digestório — entrada e perdas.</b> É a porta de entrada de <b>água, eletrólitos e nutrientes</b>: o intestino delgado absorve a maior parte, e o grosso recupera água e eletrólitos, concentrando as fezes. Também participa por suas perdas, e o sentido do distúrbio depende de onde ela ocorre: perder <b>suco gástrico</b> (vômito) é perder HCl → <b>alcalose metabólica</b> com hipocloremia e hipocalemia; perder <b>secreção intestinal</b> (diarreia) é perder bicarbonato e potássio → <b>acidose metabólica hiperclorêmica</b> com ânion gap normal e hipocalemia.<br><br><b>Integração.</b> Numa diarreia grave, os três aparecem juntos: o intestino perde HCO₃⁻ e água → o pulmão hiperventila para compensar (PaCO₂ cai) → o rim retém sódio e água, regenera bicarbonato e aumenta a excreção de NH₄⁺. Se a compensação falha, instala-se acidose descompensada e hipovolemia.',
   c:[{p:'Respiratório regula a PaCO₂ em minutos', k:['co2','co₂','ventila','pulmão','minutos','volátil','paco']},
      {p:'Renal regula o bicarbonato e excreta ácido fixo (NH₄⁺, acidez titulável)', k:['bicarbonato','hco3','hco₃','nh4','nh₄','amônio','acidez titulável','rim','renal']},
      {p:'Renal controla Na⁺, K⁺ e água via aldosterona e ADH', k:['sódio','potássio','água','aldosterona','adh','eletrólit']},
      {p:'Digestório como via de entrada de água e eletrólitos', k:['absor','entrada','intestino','ingest','delgado','grosso']},
      {p:'Relacionou vômito a alcalose e diarreia a acidose', k:['vômito','alcalose','diarreia','acidose','hcl','perde']}]}]};

/* ─── Histologia ───────────────────────────────────────────────────── */

EX['histologia/sistema-respiratorio'] = {fontes:'histologia',
 internet:[
  {t:'me', f:ADAPT, e:'O epitélio que reveste a maior parte das vias aéreas condutoras é:', a:['Pavimentoso simples','Pseudoestratificado cilíndrico ciliado com células caliciformes','Cúbico estratificado','Pavimentoso estratificado queratinizado'],
   ok:1, d:'Todas as células tocam a membrana basal, mas nem todas chegam à superfície — daí o "pseudo".', w:'É o <b>epitélio respiratório</b>: pseudoestratificado cilíndrico ciliado com caliciformes. Chama-se "pseudo" porque <i>todas</i> as células tocam a membrana basal, embora nem todas alcancem a luz — o que dá a falsa impressão de várias camadas. Exceções importantes: o <b>vestíbulo nasal</b> e as <b>pregas vocais</b> são pavimentosos estratificados (áreas de atrito), e o alvéolo é pavimentoso simples.'},
  {t:'me', f:ADAPT, e:'Os pneumócitos tipo II têm como função principal:', a:['Formar a barreira de troca gasosa','Produzir surfactante e servir de célula progenitora do epitélio alveolar','Fagocitar partículas inaladas','Secretar muco'],
   ok:1, d:'São células cuboides com corpos lamelares no citoplasma.', w:'Os <b>pneumócitos tipo II</b> são cuboides, ocupam ~5% da superfície alveolar mas são ~60% das células, e produzem o <b>surfactante</b> (dipalmitoilfosfatidilcolina), armazenado em corpos lamelares. Também funcionam como <b>células-tronco</b> do epitélio alveolar, regenerando os tipo I após lesão. Os <b>tipo I</b>, achatados, cobrem ~95% da superfície e formam a barreira de difusão. Fagocitar é papel dos <b>macrófagos alveolares</b>.'},
  {t:'me', f:ADAPT, e:'A função do surfactante pulmonar é:', a:['Aumentar a tensão superficial e facilitar o colapso alveolar','Reduzir a tensão superficial, evitando o colapso alveolar e diminuindo o trabalho respiratório','Transportar oxigênio no sangue','Filtrar partículas inaladas'],
   ok:1, d:'Pela lei de Laplace, quem tem tensão superficial alta e raio pequeno colapsa.', w:'O surfactante <b>reduz a tensão superficial</b> do filme líquido alveolar. Pela lei de Laplace (P = 2T/r), sem ele os alvéolos <b>menores</b> teriam pressão maior e se esvaziariam nos maiores. Ele age de forma dependente do raio — mais concentrado quando o alvéolo é pequeno —, o que estabiliza os alvéolos, aumenta a complacência e reduz o trabalho respiratório. Sua ausência no prematuro causa a <b>síndrome do desconforto respiratório do recém-nascido</b>.'}],
 ia:[
  {t:'me', e:'Por que os bronquíolos não possuem cartilagem nem glândulas na parede, e qual a consequência clínica disso?', a:['Porque são maiores que os brônquios','Porque seu calibre é mantido pela tração elástica do parênquima e pelo músculo liso — o que os torna colapsáveis e sujeitos a broncoespasmo','Porque não conduzem ar','Porque têm epitélio pavimentoso'],
   ok:1, d:'Sem anel cartilaginoso, o que segura o tubo aberto?', w:'Nos bronquíolos a cartilagem desaparece e a parede fica com <b>músculo liso</b> relativamente espesso, mantida aberta pela <b>tração radial</b> do parênquima elástico ao redor. Duas consequências: são o principal sítio de <b>broncoconstrição</b> (asma) e podem <b>colapsar</b> na expiração forçada quando a retração elástica se perde — exatamente o que acontece no <b>enfisema</b>, gerando aprisionamento aéreo. Surgem ainda as <b>células clara (club)</b>, secretoras e com função de detoxificação.'},
  {t:'me', e:'A barreira hemato-aérea (membrana respiratória) é formada por quais camadas, no mínimo?', a:['Apenas o endotélio capilar','Pneumócito tipo I + membranas basais fusionadas + endotélio capilar','Pneumócito tipo II + macrófago + endotélio','Muco + cílios + epitélio'],
   ok:1, d:'É a rota mais curta possível entre o ar e a hemácia — 0,2 a 0,6 µm.', w:'Na sua porção mais fina, a barreira tem <b>pneumócito tipo I</b> → <b>membranas basais fusionadas</b> do epitélio e do endotélio → <b>endotélio capilar</b>, somando 0,2–0,6 µm. Somando o filme de surfactante e o plasma, chega-se às seis camadas descritas na fisiologia. É essa finura, associada a ~70 m² de área, que torna a difusão tão eficiente — e é seu espessamento (edema, fibrose) que a compromete.'},
  {t:'ab', e:'Percorra o sistema respiratório do nariz ao alvéolo descrevendo como o epitélio muda e por que cada mudança faz sentido funcionalmente.',
   d:'A regra geral: onde há atrito, epitélio resistente; onde há defesa, muco e cílios; onde há troca, o mais fino possível.',
   g:'<b>Vestíbulo nasal:</b> epitélio <b>pavimentoso estratificado não queratinizado</b> (continuação da pele), com pelos (vibrissas) e glândulas sebáceas. Faz sentido porque é uma zona de <b>atrito</b> e de retenção das partículas maiores.<br><br><b>Cavidade nasal e cornetos:</b> <b>epitélio respiratório</b> — pseudoestratificado cilíndrico ciliado com caliciformes — sobre uma lâmina própria muito vascularizada, com plexos venosos. Função: <b>aquecer, umidificar e filtrar</b> o ar. Na região superior aparece o <b>epitélio olfatório</b>, com neurônios bipolares.<br><br><b>Faringe e laringe:</b> alternam respiratório e pavimentoso estratificado. As <b>pregas vocais</b> são pavimentosas estratificadas, porque sofrem atrito constante na fonação.<br><br><b>Traqueia e brônquios:</b> epitélio respiratório típico, com <b>anéis de cartilagem hialina</b> em C na traqueia (a parte aberta, posterior, é fechada pelo músculo traqueal, o que permite a passagem do bolo alimentar pelo esôfago) e placas cartilaginosas nos brônquios, além de glândulas seromucosas e músculo liso.<br><br><b>Bronquíolos:</b> a cartilagem e as glândulas <b>desaparecem</b>; o epitélio vai afinando de cilíndrico para <b>cúbico simples ciliado</b> e surgem as <b>células clara (club)</b>, secretoras e detoxificantes. O músculo liso torna-se proporcionalmente espesso — é o sítio do broncoespasmo.<br><br><b>Bronquíolos respiratórios:</b> transição. Epitélio <b>cúbico simples</b>, já com alvéolos brotando da parede — aqui começa a troca gasosa.<br><br><b>Ductos alveolares e alvéolos:</b> <b>epitélio pavimentoso simples</b>, o mais fino possível, formado pelos <b>pneumócitos tipo I</b> (95% da superfície, barreira de difusão) e <b>tipo II</b> (produtores de surfactante e progenitores), com <b>macrófagos alveolares</b> na luz.<br><br><b>A lógica geral:</b> à medida que se avança, o epitélio <b>afina</b> progressivamente e perde cílios, muco e cartilagem — porque a função vai deixando de ser conduzir e proteger e passa a ser <b>trocar gases</b>, e toda espessura extra atrapalharia a difusão.',
   c:[{p:'Vestíbulo nasal com epitélio pavimentoso estratificado por causa do atrito', k:['vestíbul','pavimentoso','estratificado','atrito','pelos','vibrissa']},
      {p:'Epitélio respiratório pseudoestratificado ciliado com caliciformes nas vias condutoras', k:['pseudoestratificad','ciliad','caliciform','respiratóri']},
      {p:'Traqueia e brônquios com cartilagem; bronquíolos sem cartilagem e com músculo liso', k:['cartilagem','anel','bronquíol','músculo liso','desaparece']},
      {p:'Alvéolo com epitélio pavimentoso simples e pneumócitos I e II', k:['pavimentoso simples','pneumócito','tipo i','tipo ii','alvéol']},
      {p:'Explicou a lógica do afinamento progressivo para permitir a difusão', k:['afin','fino','difus','troca','espessura','delgad']}]}]};

EX['histologia/histologia-renal-no-equilibrio-hidroeletrolitico'] = {fontes:'renal',
 internet:[
  {t:'me', f:ADAPT, e:'O corpúsculo renal é formado por:', a:['Túbulo proximal e alça de Henle','Glomérulo (tufo capilar) e cápsula de Bowman','Ducto coletor e pelve renal','Arteríola eferente e vasa recta'],
   ok:1, d:'É a parte que <i>filtra</i>, antes de qualquer túbulo.', w:'O <b>corpúsculo renal</b> = <b>glomérulo</b> (novelo de capilares entre a arteríola aferente e a eferente) + <b>cápsula de Bowman</b> (folheto parietal de epitélio pavimentoso simples e folheto visceral formado pelos <b>podócitos</b>). É onde ocorre a filtração; a reabsorção e a secreção acontecem depois, ao longo dos túbulos.'},
  {t:'me', f:ADAPT, e:'O túbulo contorcido proximal caracteriza-se histologicamente por:', a:['Epitélio pavimentoso sem microvilosidades','Epitélio cúbico simples com borda em escova proeminente e muitas mitocôndrias','Ausência de citoplasma','Epitélio estratificado ciliado'],
   ok:1, d:'É o segmento que reabsorve ~65% de tudo. Que estruturas isso exige?', w:'O <b>TCP</b> reabsorve cerca de 65% do filtrado, além de toda a glicose e os aminoácidos. Para isso tem <b>borda em escova</b> (microvilosidades que amplificam enormemente a superfície), <b>muitas mitocôndrias</b> (o transporte ativo pela Na⁺/K⁺-ATPase basolateral é caro) e interdigitações basais. Ao microscópio óptico, a luz parece "borrada" justamente pela borda em escova.'},
  {t:'me', f:ADAPT, e:'O aparelho justaglomerular é responsável por:', a:['Filtrar as proteínas plasmáticas','Secretar renina e regular a taxa de filtração glomerular, via mácula densa','Produzir surfactante','Armazenar urina'],
   ok:1, d:'É o ponto onde o túbulo distal volta a encostar no próprio glomérulo.', w:'O aparelho justaglomerular reúne as <b>células justaglomerulares</b> (musculares lisas modificadas da arteríola aferente, que produzem <b>renina</b>), a <b>mácula densa</b> (células do túbulo distal que sentem a concentração de NaCl) e as células mesangiais extraglomerulares. É a base do <b>feedback tubuloglomerular</b> e do controle do SRAA — o elo entre o rim e a pressão arterial.'}],
 ia:[
  {t:'me', e:'Por que o ducto coletor precisa de ADH para reabsorver água, enquanto o túbulo proximal não?', a:['Porque o túbulo proximal não reabsorve água','Porque o proximal tem aquaporina-1 constitutiva e reabsorve água de forma obrigatória e isosmótica; o coletor tem aquaporina-2 regulada, inserida na membrana só sob ação do ADH','Porque o ADH bloqueia o túbulo proximal','Porque o coletor não tem epitélio'],
   ok:1, d:'Uma reabsorção é obrigatória e a outra é facultativa. Onde o corpo precisa poder escolher?', w:'O <b>TCP</b> expressa <b>aquaporina-1</b> de forma constitutiva e reabsorve água <b>obrigatoriamente</b>, acompanhando o soluto — reabsorção isosmótica, que não permite ajuste. O <b>ducto coletor</b> guarda a <b>aquaporina-2</b> em vesículas intracelulares; só quando o ADH ativa o receptor V₂ (via AMPc) elas se fundem à membrana luminal. É essa reabsorção <b>facultativa</b>, no último segmento, que permite ao rim variar a osmolaridade urinária de 50 a 1.200 mOsm/kg conforme a necessidade.'},
  {t:'me', e:'Qual característica da alça de Henle permite a criação do gradiente osmótico medular?', a:['Ser totalmente impermeável à água','Ter ramo descendente permeável à água e impermeável a solutos, e ramo ascendente impermeável à água e que transporta NaCl ativamente','Ser revestida por podócitos','Não possuir vasos ao redor'],
   ok:1, d:'Duas permeabilidades opostas em dois ramos paralelos e em contracorrente.', w:'É o <b>mecanismo multiplicador em contracorrente</b>. O ramo <b>descendente</b> (delgado, pavimentoso) é permeável à <b>água</b> e o líquido vai se concentrando; o ramo <b>ascendente espesso</b> é <b>impermeável à água</b> e bombeia NaCl para o interstício pelo cotransportador <b>NKCC2</b> — alvo dos diuréticos de alça. A disposição em U multiplica esse pequeno gradiente ao longo do eixo, chegando a 1.200 mOsm/kg na papila. Os <b>vasa recta</b>, em contracorrente também, nutrem a medula sem lavar o gradiente.'},
  {t:'ab', e:'Percorra o néfron e explique o que acontece com a água e o sódio em cada segmento, relacionando com a histologia.',
   d:'Para cada segmento, pergunte: reabsorve quanto? De forma obrigatória ou regulada? E que estrutura celular permite isso?',
   g:'<b>Corpúsculo renal.</b> Filtração de ~180 L/dia, seletiva por tamanho e carga (endotélio fenestrado, membrana basal aniônica, diafragmas de fenda dos podócitos). O filtrado é isosmótico com o plasma e livre de proteínas.<br><br><b>Túbulo contorcido proximal.</b> Epitélio <b>cúbico com borda em escova</b> e muitas mitocôndrias. Reabsorve ~<b>65% do Na⁺ e da água</b>, de forma <b>isosmótica e obrigatória</b> — a água segue o soluto por aquaporina-1. Aqui também são reabsorvidos 100% da glicose e dos aminoácidos e a maior parte do bicarbonato. Não altera a osmolaridade do fluido.<br><br><b>Ramo descendente delgado da alça de Henle.</b> Epitélio <b>pavimentoso simples</b>, <b>permeável à água</b> e pouco permeável a solutos. A água sai para o interstício medular hipertônico e o fluido se <b>concentra</b> (até ~1.200 mOsm/kg na curva).<br><br><b>Ramo ascendente espesso.</b> Epitélio <b>cúbico</b>, rico em mitocôndrias, <b>impermeável à água</b>. Reabsorve ativamente ~25% do Na⁺ pelo <b>NKCC2</b>. Como sai soluto e não sai água, o fluido se <b>dilui</b> — por isso este segmento é chamado de <b>segmento diluidor</b>. É ele que gera o gradiente medular.<br><br><b>Túbulo contorcido distal.</b> Epitélio cúbico sem borda em escova, luz mais nítida. Reabsorve ~5% do Na⁺ pelo cotransportador <b>NCC</b> (alvo dos tiazídicos) e permanece impermeável à água. Contém a <b>mácula densa</b>, sensor do aparelho justaglomerular.<br><br><b>Ducto coletor.</b> Epitélio cúbico a cilíndrico com limites celulares nítidos. <b>Células principais</b> reabsorvem Na⁺ pelo canal <b>ENaC</b> sob comando da <b>aldosterona</b> (secretando K⁺ em troca) e reabsorvem água pela <b>aquaporina-2</b> sob comando do <b>ADH</b> — reabsorção <b>facultativa</b>, o ajuste fino. <b>Células intercalares</b> cuidam do equilíbrio ácido-base, secretando H⁺ ou HCO₃⁻.<br><br><b>Resultado:</b> dos 180 L filtrados, ~1,5 L viram urina, com osmolaridade ajustável entre 50 e 1.200 mOsm/kg conforme o estado de hidratação.',
   c:[{p:'Túbulo proximal reabsorve ~65% de forma isosmótica, com borda em escova', k:['proximal','65','borda em escova','isosm','obrigat','microvil']},
      {p:'Ramo descendente permeável à água, concentra o fluido', k:['descendente','permeável','água','concentra']},
      {p:'Ramo ascendente impermeável à água, transporta NaCl e dilui', k:['ascendente','impermeável','nacl','nkcc','dilui','espesso']},
      {p:'Túbulo distal e mácula densa', k:['distal','mácula densa','ncc','tiazíd']},
      {p:'Ducto coletor com aldosterona (Na⁺) e ADH (água), reabsorção facultativa', k:['coletor','aldosterona','adh','aquaporina','facultativ','enac']}]}]};

EX['histologia/regulacao-da-temperatura-corporal'] = {fontes:'histologia',
 internet:[
  {t:'me', f:ADAPT, e:'As glândulas sudoríparas écrinas diferenciam-se das apócrinas porque:', a:['As écrinas estão presentes em quase toda a pele e produzem suor aquoso, importante na termorregulação','As écrinas só existem nas axilas','As apócrinas são as principais na perda de calor','As écrinas não têm ducto'],
   ok:0, d:'Uma serve para esfriar; a outra abre no folículo piloso e tem a ver com odor.', w:'As <b>écrinas</b> distribuem-se por quase toda a superfície corporal (com destaque para palmas, plantas e fronte), abrem <b>diretamente na superfície</b> e produzem suor aquoso e hipotônico — são as glândulas da <b>termorregulação</b>. As <b>apócrinas</b> concentram-se em axilas e região anogenital, abrem no <b>folículo piloso</b>, só se tornam ativas na puberdade e produzem secreção viscosa cuja degradação bacteriana gera o odor corporal.'},
  {t:'me', f:ADAPT, e:'O centro termorregulador do corpo localiza-se:', a:['No bulbo','No hipotálamo, região pré-óptica anterior','No cerebelo','Na medula espinhal'],
   ok:1, d:'É a mesma região que cuida de sede, fome e sono.', w:'A área <b>pré-óptica do hipotálamo anterior</b> compara a temperatura do sangue que a banha com o <b>set point</b> (~37 °C) e aciona as respostas. Simplificando: o hipotálamo <b>anterior</b> comanda a <b>perda</b> de calor (vasodilatação e sudorese) e o <b>posterior</b> comanda a <b>conservação e produção</b> (vasoconstrição e calafrios).'},
  {t:'me', f:ADAPT, e:'As anastomoses arteriovenosas da pele, abundantes em mãos, pés e orelhas, servem para:', a:['Aumentar a pressão arterial','Desviar sangue diretamente das arteríolas para as vênulas, controlando a perda de calor pela superfície','Filtrar o sangue','Produzir melanina'],
   ok:1, d:'É um atalho que pula o leito capilar. Para que serviria isso na regulação térmica?', w:'As <b>anastomoses arteriovenosas</b> são conexões diretas entre arteríolas e vênulas, com espessa camada muscular e forte inervação simpática. Quando <b>abertas</b>, um grande volume de sangue chega à superfície e o calor é dissipado; quando <b>fechadas</b>, o sangue é desviado para o interior e o calor é conservado. É por isso que mãos e orelhas ficam vermelhas no calor e pálidas e frias no frio.'}],
 ia:[
  {t:'me', e:'Uma adolescente tem sudorese excessiva em axilas, palmas e plantas nas situações de estresse. Que particularidade da inervação das glândulas écrinas explica esse gatilho emocional?', a:['São inervadas pelo parassimpático','São inervadas pelo simpático, porém com fibras COLINÉRGICAS — e recebem aferência de áreas límbicas ligadas à emoção','Não têm inervação','São controladas por hormônios tireoidianos apenas'],
   ok:1, d:'É a exceção famosa da regra "simpático = noradrenalina".', w:'As glândulas sudoríparas écrinas são a exceção clássica: inervação <b>simpática</b>, mas com neurotransmissor <b>acetilcolina</b> (fibras simpáticas colinérgicas). Além do comando térmico do hipotálamo, recebem influência de áreas <b>límbicas</b> — daí a sudorese emocional das palmas e axilas, que aparece no estresse mesmo sem calor. É a base da <b>hiperidrose focal primária</b> e a razão pela qual a toxina botulínica (que bloqueia a liberação de acetilcolina) funciona no tratamento.'},
  {t:'me', e:'Por que o recém-nascido depende da termogênese sem tremor, e qual tecido a realiza?', a:['Depende dos calafrios, como o adulto','Tem musculatura e coordenação insuficientes para calafrios eficazes, e usa o tecido adiposo MARROM, rico em mitocôndrias e na proteína desacopladora UCP-1','Usa o tecido adiposo branco','Não produz calor, apenas conserva'],
   ok:1, d:'O tecido é marrom porque está cheio de mitocôndrias — e essas mitocôndrias funcionam "com defeito de propósito".', w:'O recém-nascido não consegue gerar calor por calafrios de forma eficaz, então usa o <b>tecido adiposo marrom</b> (região interescapular, cervical, perirrenal). Suas mitocôndrias expressam a <b>UCP-1 (termogenina)</b>, que <b>desacopla</b> a cadeia respiratória da síntese de ATP: o gradiente de prótons é dissipado como <b>calor</b> em vez de produzir ATP. A noradrenalina, via receptores β₃, é quem aciona o processo. Os hormônios tireoidianos são permissivos e potencializam essa termogênese.'},
  {t:'ab', e:'Descreva a via completa da termorregulação em resposta ao calor, do sensor ao efetor, indicando as estruturas histológicas envolvidas.',
   d:'Sensor → aferência → integração → eferência → efetor. Nomeie o tecido em cada etapa.',
   g:'<b>Sensores.</b> <b>Termorreceptores periféricos</b> — terminações nervosas livres na derme, com receptores TRP (TRPV para calor, TRPM8 para frio) — detectam a temperatura da pele. <b>Termorreceptores centrais</b>, na própria área pré-óptica do hipotálamo, nas vísceras abdominais e nos grandes vasos, detectam a temperatura do <b>núcleo</b>, que é a variável realmente regulada.<br><br><b>Aferência.</b> Fibras C e Aδ conduzem o sinal pelo trato espinotalâmico lateral até o hipotálamo.<br><br><b>Integração.</b> A <b>área pré-óptica do hipotálamo anterior</b> compara o valor recebido com o set point (~37 °C). Havendo desvio para cima, dispara as respostas de perda de calor.<br><br><b>Eferência e efetores:</b><br>• <b>Vasodilatação cutânea</b> — por <b>retirada do tônus vasoconstritor simpático</b> sobre as arteríolas e, sobretudo, sobre as <b>anastomoses arteriovenosas</b> de mãos, pés, orelhas e face. Elas se abrem e um grande volume de sangue chega ao <b>plexo venoso subpapilar</b> da derme, transferindo o calor do núcleo para a superfície, onde é perdido por radiação e convecção. A pele fica quente e avermelhada.<br>• <b>Sudorese</b> — as <b>glândulas sudoríparas écrinas</b>, tubulosas simples enoveladas com porção secretora na derme profunda e ducto que se abre diretamente na superfície, são ativadas por fibras <b>simpáticas colinérgicas</b>. A porção secretora produz um ultrafiltrado isotônico; o ducto reabsorve NaCl, tornando o suor <b>hipotônico</b>. Cada mL evaporado retira ~0,58 kcal. Esta é a única via que funciona quando o ambiente está mais quente que a pele.<br>• <b>Redução da termogênese</b> — queda do tônus muscular e da atividade metabólica.<br>• <b>Comportamento</b> — procurar sombra, tirar roupa, beber água fria.<br><br><b>Feedback.</b> A queda da temperatura central reduz o sinal de erro e as respostas se desligam progressivamente — retroalimentação negativa clássica. O limite do sistema é a <b>umidade</b>: se o ar está saturado, a evaporação não ocorre e nem a sudorese resolve, situação que evolui para exaustão pelo calor e insolação.',
   c:[{p:'Termorreceptores periféricos na pele e centrais no hipotálamo', k:['termorreceptor','receptor','pele','central','periféric','hipotálamo']},
      {p:'Integração na área pré-óptica do hipotálamo anterior com set point', k:['pré-óptic','hipotálamo anterior','set point','ponto de ajuste','integra']},
      {p:'Vasodilatação cutânea por retirada do tônus simpático / anastomoses AV', k:['vasodilat','anastomose','simpático','plexo','arteríola']},
      {p:'Sudorese pelas glândulas écrinas com inervação simpática colinérgica', k:['écrin','sudorese','suor','colinérg','acetilcolina']},
      {p:'Citou a evaporação como via de perda e/ou o feedback negativo', k:['evapora','0,58','calor latente','feedback','retroaliment','negativ']}]}]};

EX['histologia/siatema-cardiovascular'] = {fontes:'histologia',
 internet:[
  {t:'me', f:ADAPT, e:'As três túnicas da parede dos vasos, de dentro para fora, são:', a:['Adventícia, média e íntima','Íntima, média e adventícia','Média, íntima e adventícia','Endotélio, miocárdio e epicárdio'],
   ok:1, d:'Comece pela camada que toca o sangue.', w:'De dentro para fora: <b>túnica íntima</b> (endotélio pavimentoso simples + camada subendotelial + lâmina elástica interna), <b>túnica média</b> (músculo liso e fibras elásticas — a camada do calibre) e <b>túnica adventícia</b> (conjuntivo com vasa vasorum e nervos). No coração, as camadas equivalentes recebem outros nomes: endocárdio, miocárdio e epicárdio.'},
  {t:'me', f:ADAPT, e:'As artérias elásticas, como a aorta, caracterizam-se por:', a:['Túnica média com predomínio de lâminas elásticas fenestradas','Ausência de túnica média','Predomínio absoluto de músculo liso','Parede formada só por endotélio'],
   ok:0, d:'Elas precisam esticar na sístole e voltar na diástole.', w:'As <b>artérias elásticas</b> (aorta e seus grandes ramos) têm a túnica média dominada por <b>lâminas elásticas fenestradas</b> concêntricas. Isso permite o <b>efeito Windkessel</b>: elas se distendem na sístole, armazenando energia, e recuam na diástole, mantendo o fluxo contínuo e a pressão diastólica. Com o envelhecimento, elastina é trocada por colágeno, a aorta enrijece e surge a hipertensão sistólica isolada com pressão de pulso alargada.'},
  {t:'me', f:ADAPT, e:'Os discos intercalares do músculo cardíaco contêm junções comunicantes (gap), cuja função é:', a:['Impedir a passagem de íons entre células','Permitir o acoplamento elétrico, fazendo o miocárdio funcionar como sincício funcional','Produzir colágeno','Armazenar cálcio'],
   ok:1, d:'Como um impulso que nasce no nó sinusal alcança todas as células do átrio?', w:'Os <b>discos intercalares</b> reúnem três tipos de junção: <b>desmossomos</b> e <b>fáscias aderentes</b> (adesão mecânica, que transmite a força da contração) e <b>junções comunicantes (gap)</b>, que acoplam eletricamente as células. Por elas os íons passam diretamente de uma célula à outra, e o miocárdio se comporta como um <b>sincício funcional</b> — despolariza e contrai como uma unidade só, o que é indispensável para uma bomba eficiente.'}],
 ia:[
  {t:'me', e:'Por que os capilares contínuos do cérebro são diferentes dos fenestrados dos glomérulos e dos sinusoides do fígado?', a:['Porque têm o mesmo tipo de endotélio','Porque a permeabilidade do endotélio é ajustada à função: barreira no cérebro, filtração no rim e troca de macromoléculas no fígado','Porque só o cérebro tem capilares','Porque os sinusoides não têm endotélio'],
   ok:1, d:'A estrutura do endotélio é a resposta anatômica a "o que precisa passar aqui?".', w:'É a forma seguindo a função. Os <b>contínuos</b> com junções de oclusão apertadas e sem fenestras formam a <b>barreira hematoencefálica</b>, protegendo o neurônio. Os <b>fenestrados</b> do glomérulo têm poros que permitem <b>filtração</b> em alto volume (também aparecem em glândulas endócrinas e na mucosa intestinal). Os <b>sinusoides</b> do fígado, do baço e da medula óssea são largos, descontínuos e com membrana basal incompleta, permitindo a passagem de <b>proteínas e até de células</b>.'},
  {t:'me', e:'Qual a diferença histológica entre as fibras de Purkinje e as fibras contráteis do miocárdio?', a:['As de Purkinje são mais finas e têm mais miofibrilas','As de Purkinje são maiores, com poucas miofibrilas e muito glicogênio, o que as torna condutoras rápidas e não contráteis','As de Purkinje não têm núcleo','Não há diferença'],
   ok:1, d:'A função delas é conduzir depressa, não empurrar sangue. Que estrutura isso exige — mais ou menos aparato contrátil?', w:'As <b>fibras de Purkinje</b> são cardiomiócitos <b>modificados</b>: maiores em diâmetro, com <b>poucas miofibrilas</b> (deslocadas para a periferia), citoplasma claro e rico em <b>glicogênio</b>, e abundantes junções comunicantes. Diâmetro maior e mais junções significam menor resistência interna e, portanto, <b>condução muito rápida</b> (~4 m/s, contra ~0,5 m/s do miocárdio comum). O preço é a perda quase completa da capacidade contrátil — elas conduzem, não bombeiam.'},
  {t:'ab', e:'Compare artéria, veia e capilar quanto à estrutura das túnicas e explique como cada estrutura serve à função do vaso.',
   d:'Pressão alta pede parede grossa; retorno contra a gravidade pede válvulas; troca pede parede mínima.',
   g:'<b>Artéria.</b> Parede <b>espessa</b>, com <b>túnica média proeminente</b> e lúmen relativamente pequeno e regular (mantém-se aberto mesmo vazia, no corte histológico). As <b>elásticas</b> (aorta) têm média rica em lâminas elásticas fenestradas, que permitem o efeito Windkessel — distender na sístole e recuar na diástole, transformando o fluxo pulsátil em contínuo. As <b>musculares</b> (de distribuição) têm média rica em músculo liso e lâminas elásticas interna e externa bem definidas, distribuindo o sangue aos órgãos. As <b>arteríolas</b> têm média muscular espessa em relação ao lúmen e forte inervação simpática — são os vasos de <b>resistência</b>, controlando a PA e a distribuição de fluxo (resistência ∝ 1/r⁴).<br><br><b>Capilar.</b> Apenas <b>endotélio + membrana basal</b>, com pericitos ocasionais; diâmetro de 7–10 µm, comparável ao da hemácia. Não tem túnica média nem adventícia, porque qualquer espessura extra atrapalharia a <b>troca</b>. Três tipos, conforme a necessidade local: <b>contínuo</b> (barreira — cérebro, músculo), <b>fenestrado</b> (filtração — glomérulo, endócrinas, intestino) e <b>sinusoide</b> (passagem de macromoléculas e células — fígado, baço, medula óssea). É o único segmento onde ocorre troca, e as forças de Starling governam o movimento de líquido.<br><br><b>Veia.</b> Parede <b>fina</b> em relação a um lúmen <b>amplo e irregular</b> (frequentemente colapsado no corte), com <b>túnica média delgada</b> e <b>adventícia proporcionalmente espessa</b>, que é sua camada mais desenvolvida. Opera em baixa pressão e funciona como <b>reservatório de capacitância</b>, abrigando ~65% do volume sanguíneo. Veias de membros inferiores possuem <b>válvulas</b>, pregas da íntima que impedem o refluxo e, junto com a bomba muscular esquelética, garantem o retorno venoso contra a gravidade — sua falência é o que produz as varizes.<br><br><b>Síntese:</b> artéria = pressão e condução; capilar = troca; veia = retorno e reservatório. A espessura de cada túnica é a resposta direta a essas três exigências.',
   c:[{p:'Artéria com túnica média espessa e lúmen regular', k:['artéria','média','espess','lúmen','muscular','elástic']},
      {p:'Distinguiu artérias elásticas de musculares ou citou as arteríolas como vasos de resistência', k:['elástic','muscular','arteríol','resistência','windkessel']},
      {p:'Capilar formado só por endotélio e membrana basal, local da troca', k:['capilar','endotélio','membrana basal','troca','fino','pericito']},
      {p:'Citou os tipos de capilar (contínuo, fenestrado, sinusoide)', k:['contínu','fenestrad','sinusoid']},
      {p:'Veia com parede fina, lúmen amplo, válvulas e função de reservatório', k:['veia','válvula','fina','reservatóri','capacitância','retorno']}]}]};

EX['histologia/histologia-relacionada-ao-ritmo-circadiano'] = {fontes:'nervoso',
 internet:[
  {t:'me', f:ADAPT, e:'O marca-passo central do ritmo circadiano é:', a:['A glândula pineal','O núcleo supraquiasmático do hipotálamo','O bulbo','O tálamo'],
   ok:1, d:'Fica logo acima do quiasma óptico — daí o nome.', w:'O <b>núcleo supraquiasmático (NSQ)</b>, no hipotálamo anterior sobre o quiasma óptico, é o <b>relógio central</b>. Ele gera um ritmo endógeno de ~24 h por alças de transcrição-tradução dos genes CLOCK, BMAL1, PER e CRY, e é sincronizado ("arrastado") pela luz. A <b>pineal</b> é o efetor: recebe o comando do NSQ e secreta <b>melatonina</b>.'},
  {t:'me', f:ADAPT, e:'A melatonina é produzida pela glândula pineal e sua secreção:', a:['Aumenta durante o dia','Aumenta durante a noite, na ausência de luz','É constante nas 24 horas','Depende apenas da alimentação'],
   ok:1, d:'É chamada de "hormônio do escuro".', w:'A melatonina é o <b>hormônio da escuridão</b>: sua síntese sobe no início da noite, atinge o pico entre 2 e 4 h e cai ao amanhecer. A luz — sobretudo a de comprimento de onda azul, captada pelas células ganglionares retinianas com <b>melanopsina</b> — chega ao NSQ pelo trato retino-hipotalâmico e <b>suprime</b> a secreção. É por isso que telas à noite atrapalham o sono.'},
  {t:'me', f:ADAPT, e:'A via que leva a informação luminosa da retina ao núcleo supraquiasmático é:', a:['O trato óptico até o córtex visual','O trato retino-hipotalâmico','O nervo vago','O trato espinotalâmico'],
   ok:1, d:'É uma via separada da visão consciente.', w:'O <b>trato retino-hipotalâmico</b> é uma via <b>independente</b> da percepção visual consciente: parte de células ganglionares intrinsecamente fotossensíveis, que contêm <b>melanopsina</b>, e projeta direto ao NSQ. Por isso muitas pessoas cegas por lesão de cones e bastonetes preservam a sincronização circadiana — a via da imagem e a via do relógio são diferentes.'}],
 ia:[
  {t:'me', e:'Um trabalhador noturno apresenta insônia, alterações metabólicas e ganho de peso. Como o desalinhamento circadiano explica isso?', a:['Apenas por má alimentação','Porque os relógios periféricos (fígado, tecido adiposo, pâncreas) ficam dessincronizados do NSQ, alterando a secreção de cortisol, insulina, leptina e grelina','Porque a pineal deixa de existir','Porque a luz artificial aumenta o metabolismo basal'],
   ok:1, d:'O NSQ é o maestro, mas cada órgão tem seu próprio relógio. O que acontece quando eles deixam de tocar juntos?', w:'Praticamente todos os tecidos possuem <b>relógios periféricos</b>, normalmente sincronizados pelo NSQ, pela luz e pelos horários de alimentação. No trabalho noturno, luz e comida chegam fora de fase e esses relógios se dessincronizam. As consequências são bem documentadas: alteração do ritmo de <b>cortisol</b>, redução da <b>sensibilidade à insulina</b> (a tolerância à glicose é pior à noite), queda da <b>leptina</b> e aumento da <b>grelina</b> — mais fome, mais peso. O trabalho em turnos é hoje classificado como fator de risco metabólico e cardiovascular.'},
  {t:'me', e:'Qual é a característica histológica marcante da glândula pineal, útil para identificá-la em lâmina?', a:['Presença de folículos com coloide','Presença de pinealócitos e de concreções calcificadas (areia cerebral / corpora arenacea)','Epitélio pseudoestratificado ciliado','Cordões de células com borda em escova'],
   ok:1, d:'É uma glândula que aparece no raio-X e na tomografia por causa desses depósitos.', w:'A pineal é formada por <b>pinealócitos</b> (células neuroendócrinas modificadas, com prolongamentos) e neuróglia, e sua marca registrada em lâmina são as <b>concreções calcificadas</b> — a <b>areia cerebral</b> (<i>corpora arenacea</i>), depósitos de fosfato e carbonato de cálcio que aumentam com a idade. São radiopacas e servem de marco da linha média nos exames de imagem. Folículos com coloide são da tireoide; borda em escova, do túbulo proximal.'},
  {t:'ab', e:'Explique como a luz captada pela retina resulta em supressão da melatonina, nomeando as estruturas da via.',
   d:'São cinco escalas: retina → hipotálamo → medula → gânglio cervical superior → pineal.',
   g:'<b>1. Retina.</b> A luz é captada não pelos cones e bastonetes da visão consciente, mas por <b>células ganglionares intrinsecamente fotossensíveis</b>, que contêm o fotopigmento <b>melanopsina</b> — especialmente sensível à luz azul (~480 nm).<br><br><b>2. Trato retino-hipotalâmico.</b> Os axônios dessas células formam uma via própria, que se separa do trato óptico e projeta diretamente ao <b>núcleo supraquiasmático (NSQ)</b> do hipotálamo. Isso explica por que pessoas cegas por degeneração de fotorreceptores podem manter o ritmo circadiano preservado.<br><br><b>3. NSQ.</b> O relógio central é <b>arrastado</b> (sincronizado) pelo sinal luminoso e, em resposta à luz, <b>inibe</b> a via que estimula a pineal.<br><br><b>4. Via eferente multissináptica.</b> O NSQ projeta ao <b>núcleo paraventricular</b> do hipotálamo → coluna intermediolateral da medula torácica alta → <b>gânglio cervical superior</b> (simpático) → fibras pós-ganglionares noradrenérgicas que inervam a <b>glândula pineal</b>.<br><br><b>5. Pineal.</b> No escuro, a noradrenalina liberada ativa receptores β₁ nos <b>pinealócitos</b>, elevando o AMPc e a expressão da enzima <b>AANAT</b> (arilalquilamina N-acetiltransferase), que é a etapa limitante da conversão de serotonina em <b>melatonina</b>. Na presença de luz, o NSQ inibe essa via: cai a noradrenalina, cai a AANAT e a <b>síntese de melatonina é suprimida</b> em minutos.<br><br><b>Nota:</b> a melatonina é lipossolúvel, não é armazenada e difunde-se assim que é produzida — por isso sua concentração plasmática reflete quase instantaneamente o estado de iluminação.',
   c:[{p:'Células ganglionares com melanopsina captam a luz', k:['melanopsina','ganglionar','fotossensí','azul','retina']},
      {p:'Trato retino-hipotalâmico leva ao núcleo supraquiasmático', k:['retino-hipotalâmic','retinohipotal','supraquiasmátic','nsq']},
      {p:'Via eferente simpática pelo gânglio cervical superior', k:['cervical superior','simpátic','gânglio','paraventricular','medula']},
      {p:'Noradrenalina age no pinealócito e regula a síntese de melatonina', k:['noradrenalina','pinealócito','melatonina','aanat','serotonina']},
      {p:'Concluiu que a luz suprime e o escuro estimula a melatonina', k:['suprime','inibe','escuro','noite','reduz','aumenta à noite']}]}]};
</script>
