<script>
/* ══════════════════════════════════════════════════════════════════════
   Banco de exercícios — fontes + Pequenos grupos
   t:'me' múltipla escolha · t:'ab' aberta (corrigida por critérios)
   ══════════════════════════════════════════════════════════════════════ */
window.EX = window.EX || {};
window.FONTES = {
 homeostase:[
  {t:'SISU.pro — Questões de fisiologia humana com gabarito comentado', u:'https://www.sisu.pro.br/exercicios/questoes-de-fisiologia-humana-com-gabarito.html', d:'sisu.pro.br'},
  {t:'Seu Saber — Homeostase: resumo, aula e exercícios', u:'https://seusaber.com.br/homeostase-resumo-aula-e-exercicios/', d:'seusaber.com.br'},
  {t:'QConcursos — Mecanismos de equilíbrio ácido-básico e homeostase', u:'https://www.qconcursos.com/questoes-de-concursos/questoes/192cdd50-5c', d:'qconcursos.com'}],
 acidobase:[
  {t:'FCAV/UNESP — Equilíbrio ácido-base: exercícios resolvidos (PDF)', u:'https://www.fcav.unesp.br/Home/departamentos/tecnologia/LUCIANAMARIASARAN/equilibrio-acido-base_exercicios-resolvidos.pdf', d:'unesp.br'},
  {t:'Sanar — Como resolver questões de distúrbios ácido-base na residência', u:'https://sanarmed.com/como-resolver-questoes-de-disturbios-acido-base-nas-provas-de-residencia-colunistas/', d:'sanarmed.com'},
  {t:'SISU.pro — Fisiologia humana com gabarito comentado', u:'https://www.sisu.pro.br/exercicios/questoes-de-fisiologia-humana-com-gabarito.html', d:'sisu.pro.br'}],
 cardio:[
  {t:'Artmed — Regulação da pressão arterial: reflexo barorreceptor', u:'https://artmed.com.br/artigos/regulacao-da-pressao-arterial-reflexo-barorreceptor', d:'artmed.com.br'},
  {t:'Sanar — Bases fisiológicas da pressão arterial', u:'https://sanarmed.com/bases-fisiologicas-da-pressao-arterial-e-mecanismos-iniciais-dos-diureticos-colunistas/', d:'sanarmed.com'},
  {t:'Rev Bras Hipertensão — Controle neural da circulação (PDF)', u:'http://departamentos.cardiol.br/dha/revista/7-2/004.pdf', d:'cardiol.br'},
  {t:'Khan Academy — Regulação da PA com barorreceptores', u:'https://pt.khanacademy.org/science/health-and-medicine/circulatory-system/blood-pressure-control/v/regulation-of-blood-pressure-with-baroreceptors', d:'khanacademy.org'}],
 semio:[
  {t:'Sanar — Exame físico: inspeção geral e sinais vitais', u:'https://sanarmed.com/inspecao-geral-e-sinais-vitais/', d:'sanarmed.com'},
  {t:'Estratégia MED — Sinais vitais: semiologia e valores de referência', u:'https://med.estrategia.com/portal/conteudos-gratis/ciclo-basico/resumo-de-sinais-vitais-semiologia-valores-de-referencia-e-mais/', d:'estrategia.com'},
  {t:'Gran Cursos — Questões de exame físico e semiologia', u:'https://questoes.grancursosonline.com.br/questoes-de-concursos/enfermagem-exame-fisico-semiologia-428442', d:'grancursosonline.com.br'},
  {t:'Studocu — Questões de semiologia médica (provas 1 e 2)', u:'https://www.studocu.com/pt-br/document/universidade-de-itauna/semiologia-medica-ii/questoes-de-semiologia-provas-1-e-2/13875935', d:'studocu.com'}],
 respiratorio:[
  {t:'QConcursos — Sistema respiratório humano', u:'https://www.qconcursos.com/questoes-de-concursos/disciplinas/biologia-biologia/sistema-respiratorio-humano/questoes', d:'qconcursos.com'},
  {t:'Estratégia Vestibulares — 11 questões de sistema respiratório', u:'https://vestibulares.estrategia.com/portal/atualidades-e-dicas/11-questoes-sobre-sistema-respiratorio-que-ja-cairam-nos-vestibulares-e-enem/', d:'estrategia.com'},
  {t:'Beduka — 14 exercícios de sistema respiratório com gabarito', u:'https://beduka.com/blog/exercicios/biologia-exercicios/exercicios-sobre-sistema-respiratorio/', d:'beduka.com'},
  {t:'Só Exercícios — UNESP, trocas gasosas e respiração', u:'https://soexercicios.com.br/plataforma/questoes-de-vestibular/UNESP/15601-15598/-trocas-gasosas-respiracao-fisiologia-geral-rec-/1', d:'soexercicios.com.br'}],
 endocrino:[
  {t:'Estratégia Vestibulares — 13 questões de sistema endócrino', u:'https://vestibulares.estrategia.com/portal/atualidades-e-dicas/13-questoes-sobre-o-sistema-endocrino-que-ja-cairam-nos-vestibulares-e-enem/', d:'estrategia.com'},
  {t:'Beduka — Resumo e exercícios de sistema endócrino com gabarito', u:'https://beduka.com/blog/exercicios/biologia-exercicios/exercicios-sobre-sistema-endocrino/', d:'beduka.com'},
  {t:'Vestibulando Web — Sistema endócrino e hormônios', u:'https://www.vestibulandoweb.com.br/biologia/sistema-endocrino/', d:'vestibulandoweb.com.br'},
  {t:'QConcursos — Sistema endócrino humano', u:'https://www.qconcursos.com/questoes-de-concursos/disciplinas/biologia-biologia/sistema-endocrino-humano/questoes', d:'qconcursos.com'},
  {t:'UFPR — Eixo hipotálamo-hipófise (PDF)', u:'https://bio.ufpr.br/fisiologia/wp-content/uploads/sites/37/2021/04/Jogo_endocrino_parte-1-1.pdf', d:'ufpr.br'}],
 renal:[
  {t:'UFRGS — Estudo dirigido sobre fisiologia renal (PDF)', u:'https://www.ufrgs.br/fisiologiacelular/site/arqs/ENSINO/Estudo%20Dirigido%20sobre%20Fisiologia%20Renal.pdf', d:'ufrgs.br'},
  {t:'Sanar — Fisiologia renal: anatomia e funções', u:'https://sanarmed.com/fisiologia-renal-colunistas/', d:'sanarmed.com'},
  {t:'Exercícios Web — Simulado de anatomia do sistema urinário', u:'https://exerciciosweb.com.br/anatomia/simulado-sobre-anatomia-do-sistema-urinario/', d:'exerciciosweb.com.br'},
  {t:'QConcursos — Fisiologia renal', u:'https://www.qconcursos.com/questoes-de-concursos/questoes/4a3b6e00-25', d:'qconcursos.com'}],
 digestorio:[
  {t:'Toda Matéria — Exercícios sobre sistema digestório com gabarito', u:'https://www.todamateria.com.br/exercicios-sistema-digestorio/', d:'todamateria.com.br'},
  {t:'Beduka — Exercícios sobre sistema digestório com gabarito', u:'https://beduka.com/blog/exercicios/biologia-exercicios/exercicios-sobre-sistema-digestorio/', d:'beduka.com'},
  {t:'Sanar — Fisiologia do trato gastrointestinal', u:'https://sanarmed.com/fisiologia-do-trato-gastrointestinal-mecanismos-basicos-e-aplicados-colunistas/', d:'sanarmed.com'},
  {t:'USP/Redefor — Fisiologia do sistema digestório (PDF)', u:'https://midia.atp.usp.br/impressos/redefor/EnsinoBiologia/Fisio_2011_2012/Fisiologia_v2_semana04.pdf', d:'usp.br'}],
 nervoso:[
  {t:'Estratégia Vestibulares — 11 questões de sistema nervoso', u:'https://vestibulares.estrategia.com/portal/atualidades-e-dicas/11-questoes-sobre-sistema-nervoso-que-ja-cairam-nos-vestibulares-e-enem/', d:'estrategia.com'},
  {t:'Toda Matéria — Exercícios sobre o sistema nervoso explicados', u:'https://www.todamateria.com.br/exercicios-sistema-nervoso/', d:'todamateria.com.br'},
  {t:'Só Exercícios — UFU, sistema nervoso autônomo', u:'https://soexercicios.com.br/plataforma/questoes-de-vestibular/UFU/9161746-8540981/-identificacao-por-tabelas-biologia-t-acoes-do-sistema-nervoso-autonomo-simpatico-f-acoes-do-sistema-nervoso-autonomo-parassimpatico-f-/1', d:'soexercicios.com.br'},
  {t:'QConcursos — Sistema nervoso autônomo', u:'https://www.qconcursos.com/questoes-de-concursos/questoes/5fc8e6ec-93', d:'qconcursos.com'}],
 histologia:[
  {t:'UESC — Atlas de histologia: exercícios por tecido', u:'https://www.uesc.br/projetos/atlas-histologia/index.php?item=conteudo_formularios_exercicios.php', d:'uesc.br'},
  {t:'UNIFAL-MG — Histologia Interativa: questionários', u:'https://www.unifal-mg.edu.br/histologiainterativa/questionario-9/', d:'unifal-mg.edu.br'},
  {t:'Exercícios Web — Tecido conjuntivo: 10 exercícios com gabarito', u:'https://exerciciosweb.com.br/histologia/tecido-conjuntivo-exercicios-histologia-gabarito/', d:'exerciciosweb.com.br'},
  {t:'Beduka — Exercícios de histologia com gabarito', u:'https://beduka.com/blog/exercicios/biologia-exercicios/exercicios-de-histologia/', d:'beduka.com'}],
 lipidios:[
  {t:'Projeto Ágatha Edu — Questões de lipídios (bioquímica)', u:'https://www.projetoagathaedu.com.br/questoes-vestibular/biologia/bioquimica/lipidios.php', d:'projetoagathaedu.com.br'},
  {t:'Toda Matéria — Exercícios sobre lipídios com resolução', u:'https://www.todamateria.com.br/exercicios-sobre-lipidios/', d:'todamateria.com.br'}]
};

window.ADAPT = 'Adaptada do estilo dos bancos públicos';

/* ─── Pequenos grupos ──────────────────────────────────────────────── */

EX['pequenos-grupos/funcoes-do-organismo'] = {fontes:'homeostase',
 internet:[
  {t:'me', f:ADAPT, e:'Homeostase pode ser definida como:', a:['A ausência total de variação no meio interno','A manutenção de um meio interno relativamente constante, apesar das variações do ambiente externo','O aumento progressivo da temperatura corporal durante o exercício','A capacidade de uma célula se dividir indefinidamente'],
   ok:1, d:'Repare na palavra que Guyton usa: <b>relativamente</b> constante. Homeostase não é imobilidade.', w:'A definição de Guyton é a manutenção de condições <b>relativamente</b> constantes no meio interno. A alternativa A erra justamente aí: as variáveis oscilam o tempo todo dentro de uma faixa estreita — o que é constante é a <i>faixa</i>, não o valor exato. Sem essa oscilação não haveria como um sensor detectar desvio nenhum.'},
  {t:'me', f:ADAPT, e:'Os três componentes básicos de qualquer alça de controle homeostático são:', a:['Estímulo, resposta e adaptação','Receptor (sensor), centro integrador e efetor','Aferência, eferência e retroalimentação positiva','Hipotálamo, hipófise e glândula-alvo'],
   ok:1, d:'Pense num termostato: alguém mede, alguém decide, alguém age.', w:'<b>Sensor</b> detecta o desvio → <b>centro integrador</b> (frequentemente o hipotálamo) compara com o ponto de ajuste e decide → <b>efetor</b> executa a correção. A alternativa D descreve um eixo hormonal específico, que é <i>um exemplo</i> dessa estrutura, não a estrutura geral.'},
  {t:'me', f:ADAPT, e:'O meio interno, no sentido fisiológico do termo, corresponde a:', a:['Ao líquido intracelular','Ao líquido extracelular, que banha as células','Ao conteúdo do trato gastrointestinal','Ao plasma sanguíneo exclusivamente'],
   ok:1, d:'Claude Bernard criou o termo para o líquido que fica <i>entre</i> as células e o mundo.', w:'O <b>meio interno</b> é o <b>líquido extracelular</b> — interstício mais plasma. É ele que a célula "enxerga" e é a composição dele que a homeostase defende. Curiosidade importante: o conteúdo do tubo digestivo é, tecnicamente, <b>meio externo</b> — só entra no corpo depois de absorvido.'}],
 ia:[
  {t:'me', e:'Uma pessoa entra numa sauna a 90 °C e sua temperatura central sobe apenas 0,3 °C em 15 minutos. Isso demonstra que:', a:['A temperatura corporal é fixa e não varia','Os mecanismos homeostáticos de perda de calor foram acionados e mantiveram a variável regulada dentro da faixa','A homeostase falhou, pois houve variação','O ambiente externo não influencia o meio interno'],
   ok:1, d:'0,3 °C de variação para 70 °C de diferença ambiental é muito ou pouco?', w:'Um desvio de 0,3 °C diante de um estresse térmico gigantesco é a <b>prova</b> de que a regulação funcionou: vasodilatação cutânea e sudorese dissiparam quase todo o calor ganho. Homeostase é justamente isso — variar pouco, não variar zero. Se a temperatura não subisse nada, não haveria erro para o sensor detectar e nenhuma correção seria disparada.'},
  {t:'me', e:'Qual das situações abaixo é um exemplo de retroalimentação POSITIVA fisiológica?', a:['Regulação da glicemia pela insulina','Controle da pressão arterial pelos barorreceptores','Contrações uterinas no trabalho de parto amplificadas pela ocitocina','Regulação da temperatura pela sudorese'],
   ok:2, d:'Feedback positivo <b>amplifica</b> o desvio até um evento encerrar o ciclo. Qual dessas termina com um "fim" claro?', w:'No parto, a distensão do colo libera ocitocina, que aumenta a contração, que distende mais o colo — o ciclo se <b>amplifica</b> até o nascimento encerrá-lo. Os outros três exemplos são feedback <b>negativo</b>: corrigem o desvio e se desligam. Os outros dois exemplos clássicos de feedback positivo são a cascata de coagulação e o potencial de ação (influxo de Na⁺).'},
  {t:'ab', e:'Explique a diferença entre controle local, controle de longa distância e controle antecipatório (feedforward), dando um exemplo de cada.',
   d:'Pense em <i>quem</i> dá a ordem: a própria célula vizinha, um nervo/hormônio distante, ou uma previsão do que vai acontecer.',
   g:'<b>Controle local (parácrino/autócrino):</b> a resposta é gerada e executada no próprio tecido, sem participação do sistema nervoso ou endócrino. Exemplo: a hipóxia tecidual local causa vasodilatação arteriolar naquele leito, aumentando o fluxo apenas onde há necessidade.<br><br><b>Controle de longa distância (reflexo):</b> a informação sai do tecido, é integrada em um centro (SNC ou glândula endócrina) e volta como resposta neural ou hormonal. Exemplo: queda da pressão arterial → barorreceptores → bulbo → aumento do tônus simpático → vasoconstrição e taquicardia.<br><br><b>Controle antecipatório (feedforward):</b> a resposta é disparada <i>antes</i> de a variável se alterar, com base em um sinal preditivo — ele não corrige um erro, ele evita que o erro aconteça. Exemplo: a salivação e a secreção gástrica que começam ao ver ou cheirar a comida (fase cefálica da digestão); ou o aumento da frequência cardíaca no instante anterior à largada de uma corrida.',
   c:[{p:'Controle local age no próprio tecido, sem SNC nem hormônio sistêmico', k:['local','parácrin','próprio tecido','sem o sistema nervoso']},
      {p:'Controle de longa distância usa via neural e/ou endócrina com centro integrador', k:['longa distância','reflexo','nervos','hormôn','barorrecep','sistema nervoso']},
      {p:'Feedforward antecipa o desvio em vez de corrigi-lo', k:['antecipat','feedforward','antes','prevê','previsão','antecipa']},
      {p:'Deu um exemplo concreto de cada tipo', k:['exemplo','saliva','vasodilat','barorrecep','corrida','comida']}]}]};

EX['pequenos-grupos/homeostase-e-integracao-dos-sistemas'] = {fontes:'homeostase',
 internet:[
  {t:'me', f:ADAPT, e:'Sobre o ponto de ajuste (set point) de uma variável regulada, é correto afirmar que:', a:['É um valor absolutamente fixo ao longo da vida','Pode ser deslocado fisiologicamente, como ocorre na febre','Só existe para a temperatura corporal','É determinado exclusivamente pelos rins'],
   ok:1, d:'A febre é o exemplo clássico de um set point <i>reprogramado</i>.', w:'O ponto de ajuste é <b>ajustável</b>. Na febre, a PGE₂ hipotalâmica eleva o set point e o corpo passa a defender ativamente a temperatura mais alta — daí os calafrios. Também varia com o ritmo circadiano, com o ciclo menstrual e com a aclimatação. Todas as variáveis reguladas têm set point, não só a temperatura.'},
  {t:'me', f:ADAPT, e:'A perda da homeostase leva a:', a:['Adaptação sem consequências','Disfunção celular, doença e, em casos extremos, morte','Aumento automático do metabolismo basal','Ativação exclusiva do sistema imune'],
   ok:1, d:'Pense no que acontece com uma enzima quando o pH sai de 7,4.', w:'A homeostase existe porque as reações celulares só funcionam numa faixa estreita de pH, temperatura, osmolaridade e concentração iônica. Fora dela, proteínas mudam de conformação, enzimas perdem atividade e gradientes de membrana se dissipam. O resultado é <b>disfunção → doença → morte</b>. Não é um conceito abstrato: é o que se mede na gasometria.'},
  {t:'me', f:ADAPT, e:'Qual sistema é considerado o principal centro integrador da homeostase, recebendo aferências e comandando respostas neurais e endócrinas?', a:['Sistema digestório','Hipotálamo','Medula óssea','Sistema tegumentar'],
   ok:1, d:'Ele fica no diencéfalo e controla sede, fome, temperatura, sono e a hipófise.', w:'O <b>hipotálamo</b> é a ponte entre o sistema nervoso e o endócrino: recebe informação de osmorreceptores, termorreceptores e barorreceptores, e responde tanto por via neural (autonômica) quanto por via hormonal (liberando fatores para a hipófise e produzindo ADH e ocitocina). É o centro integrador por excelência da homeostase.'}],
 ia:[
  {t:'me', e:'Durante uma hemorragia de 20% da volemia, qual é a ORDEM correta das respostas compensatórias?', a:['Retenção renal de água → barorreflexo → SRAA','Barorreflexo (segundos) → SRAA e ADH (minutos a horas) → retenção renal de sal e água (horas a dias)','SRAA → barorreflexo → resposta isquêmica do SNC','Todas ocorrem simultaneamente, com a mesma velocidade'],
   ok:1, d:'Ordene pela velocidade do mecanismo: nervo, hormônio, rim.', w:'A regra que organiza todo o capítulo: <b>nervos em segundos, hormônios em horas, rim em dias</b>. Primeiro o barorreflexo dispara o simpático; depois entram SRAA, ADH e o deslocamento de líquido do interstício para o capilar; por último o rim retém sódio e água para reconstituir o volume. A resposta isquêmica do SNC só entra se a PA cair abaixo de ~60 mmHg.'},
  {t:'me', e:'Por que a maioria das alças homeostáticas usa retroalimentação NEGATIVA e não positiva?', a:['Porque o feedback positivo não existe no corpo humano','Porque o feedback negativo é autolimitado e estabiliza a variável, enquanto o positivo a afasta cada vez mais do ponto de ajuste','Porque o feedback negativo é mais rápido','Porque o feedback positivo consome mais energia'],
   ok:1, d:'Qual dos dois desliga sozinho quando a variável volta ao normal?', w:'O feedback negativo é <b>autolimitado</b>: à medida que a variável se aproxima do set point, o sinal de erro diminui e a resposta se desliga sozinha — exatamente o que se quer de um sistema estável. O positivo <b>amplifica</b> o desvio e por isso só é útil quando existe um evento externo para encerrar o ciclo (o nascimento, a formação do coágulo, a repolarização). Sem esse fim, feedback positivo é sinônimo de descompensação — como no choque irreversível.'},
  {t:'ab', e:'Um paciente chega ao pronto-socorro com desidratação grave por diarreia de três dias. Descreva as respostas homeostáticas esperadas, separando-as por tempo de instalação.',
   d:'Percorra o eixo: quem detecta (sensor), quem integra e quem executa — e faça isso em três janelas de tempo.',
   g:'<b>Segundos a minutos (neural):</b> a perda de volume reduz o retorno venoso, o débito cardíaco e a pressão arterial. Os barorreceptores do seio carotídeo e do arco aórtico descarregam menos, desinibindo o simpático: taquicardia, aumento da contratilidade e vasoconstrição periférica (extremidades frias, enchimento capilar lentificado). Nesta fase a PA ainda pode estar normal — é o choque compensado.<br><br><b>Minutos a horas (endócrino):</b> a queda da perfusão renal e do NaCl na mácula densa, somada ao estímulo simpático β₁, libera renina → angiotensina II → vasoconstrição e aldosterona → reabsorção de Na⁺ no túbulo coletor. Os barorreceptores e os osmorreceptores liberam ADH, que reabsorve água livre e concentra a urina. O centro da sede é ativado. Há ainda deslocamento de líquido do interstício para o capilar.<br><br><b>Horas a dias (renal):</b> o rim retém sódio e água até restaurar o volume extracelular, com urina de baixo volume e alta osmolaridade. Se houve perda importante de bicarbonato pelas fezes, instala-se acidose metabólica com ânion gap normal (hiperclorêmica), compensada por hiperventilação.<br><br><b>Limites:</b> se a perda ultrapassar a capacidade de compensação, a PA cai, surge hipoperfusão tecidual, metabolismo anaeróbio e acidose lática — falha homeostática.',
   c:[{p:'Resposta neural rápida: barorreflexo, taquicardia e vasoconstrição', k:['barorrecep','simpático','taquicardia','vasoconstri','frequência cardíaca']},
      {p:'Resposta hormonal: SRAA, aldosterona e ADH', k:['renina','angiotensina','aldosterona','adh','vasopressina','sraa']},
      {p:'Resposta renal: retenção de sódio e água, urina concentrada', k:['rim','renal','retenção','urina','sódio','oligúria','concentra']},
      {p:'Citou a sede como mecanismo comportamental', k:['sede']},
      {p:'Mencionou o limite da compensação ou a acidose', k:['acidose','lactato','choque','descompens','falha','limite']}]}]};

EX['pequenos-grupos/osmolaridade-temperatura-e-ph-1'] = {fontes:'acidobase',
 internet:[
  {t:'me', f:ADAPT, e:'A osmolaridade plasmática normal e o principal soluto que a determina são, respectivamente:', a:['180–220 mOsm/kg e a glicose','285–295 mOsm/kg e o sódio','300–350 mOsm/kg e a ureia','250–270 mOsm/kg e o potássio'],
   ok:1, d:'Na fórmula 2×[Na⁺] + glicose/18 + ureia/6, qual termo domina o resultado?', w:'A faixa é <b>285–295 mOsm/kg</b> e quem manda é o <b>sódio</b>: como a fórmula multiplica a natremia por 2 (para contar os ânions que a acompanham), 140 × 2 = 280 dos ~290 totais. Glicose e ureia contribuem com ~5 cada. O potássio é o cátion <i>intracelular</i>, e por isso quase não aparece na osmolaridade plasmática.'},
  {t:'me', f:ADAPT, e:'O aumento de 1–2% na osmolaridade plasmática provoca principalmente:', a:['Liberação de aldosterona','Secreção de ADH e aumento da reabsorção renal de água','Aumento do peptídeo natriurético atrial','Inibição da sede'],
   ok:1, d:'Qual sensor é tão fino que responde a uma variação de apenas 1%?', w:'Os <b>osmorreceptores hipotalâmicos</b> são extremamente sensíveis — 1 a 2% já dispara <b>ADH</b>, que insere aquaporina-2 no ducto coletor e reabsorve água livre. O limiar da sede é mais alto (~290–295). A aldosterona regula <b>volume</b> (sódio), não concentração; o PNA faz o oposto do que a questão pede.'},
  {t:'me', f:ADAPT, e:'Em ambiente com temperatura de 40 °C, o principal mecanismo de perda de calor passa a ser:', a:['Radiação','Condução','Convecção','Evaporação'],
   ok:3, d:'Se o ar está mais quente que a pele, para que lado o calor flui nos outros três mecanismos?', w:'Radiação, condução e convecção dependem de o corpo estar mais quente que o ambiente. A 40 °C o gradiente se inverte e esses três passam a <b>trazer</b> calor. Sobra a <b>evaporação</b>, que funciona contra o gradiente térmico (0,58 kcal por mL de suor evaporado). Por isso calor úmido é tão perigoso: a umidade bloqueia justamente a única via que ainda funcionava.'}],
 ia:[
  {t:'me', e:'Paciente diabético com glicemia de 600 mg/dL apresenta sódio de 128 mEq/L. Ele tem hiponatremia verdadeira?', a:['Sim, e precisa de salina hipertônica','Não: é hiponatremia dilucional pela hiperglicemia — corrigido, o sódio é ≈ 136 mEq/L','Sim, causada pela poliúria osmótica','Não é possível avaliar sem a osmolaridade urinária'],
   ok:1, d:'Some 1,6 mEq de sódio para cada 100 mg/dL de glicose acima de 100.', w:'A glicose é osmol <b>efetivo</b>: fica restrita ao extracelular e puxa água de dentro da célula, diluindo o sódio. Correção: (600−100)/100 × 1,6 = 8 → 128 + 8 = <b>136 mEq/L</b>. O sódio corporal está normal. Tratar com hipertônica seria um erro grave — corrige-se a glicemia e o sódio sobe sozinho.'},
  {t:'me', e:'Qual é a diferença fisiopatológica entre febre e hipertermia?', a:['A febre é sempre mais alta','Na febre o set point hipotalâmico sobe e o corpo busca ativamente a nova temperatura; na hipertermia o set point é normal e a dissipação de calor falhou','Febre é bacteriana, hipertermia é viral','Não há diferença fisiológica'],
   ok:1, d:'Em qual das duas o antitérmico funciona — e por quê?', w:'Na <b>febre</b>, IL-1, IL-6 e TNF-α elevam a PGE₂ hipotalâmica e o set point sobe; o corpo então trabalha para chegar lá, com calafrios e vasoconstrição. Antitérmico funciona porque inibe a COX. Na <b>hipertermia</b> (insolação, hipertermia maligna, síndrome neuroléptica maligna) o set point está normal e a produção supera a dissipação: antitérmico é inútil, o tratamento é resfriamento físico.'},
  {t:'ab', e:'Explique por que a ureia elevada NÃO desidrata as células, enquanto a glicose elevada SIM — e como isso aparece nas fórmulas de osmolaridade.',
   d:'A pergunta-chave é: o soluto consegue atravessar a membrana celular livremente?',
   g:'Um soluto só puxa água entre compartimentos se ficar <b>restrito</b> a um deles. A <b>ureia</b> atravessa livremente as membranas celulares e se equilibra dos dois lados em minutos: ela eleva a osmolaridade <i>medida</i> igualmente no LIC e no LEC, sem criar gradiente. É por isso que se diz que a ureia é um <b>osmol inefetivo</b> — o paciente urêmico não tem células desidratadas por causa dela.<br><br>A <b>glicose</b>, na ausência de insulina, não entra livremente na maioria das células (depende de GLUT4 nos tecidos insulino-dependentes). Ela fica retida no extracelular, cria gradiente osmótico <b>efetivo</b> e puxa água de dentro da célula para fora — desidratando o meio intracelular e, ao mesmo tempo, diluindo o sódio plasmático (hiponatremia dilucional).<br><br>Nas fórmulas: a <b>osmolaridade calculada</b> soma tudo — 2×[Na⁺] + glicose/18 + ureia/6 — porque mede partículas. Já a <b>tonicidade (osmolaridade efetiva)</b> exclui a ureia — 2×[Na⁺] + glicose/18 — porque só interessa o que movimenta água. É a tonicidade, e não a osmolaridade total, que determina se a célula incha ou murcha.',
   c:[{p:'Ureia atravessa a membrana livremente e se equilibra dos dois lados', k:['atravessa','livremente','permeia','equilibra','difunde','entra na célula']},
      {p:'Chamou a ureia de osmol inefetivo', k:['inefetivo','não efetivo','ineficaz']},
      {p:'Glicose fica restrita ao extracelular e cria gradiente efetivo', k:['restrit','extracelular','efetivo','gradiente','não entra','insulina']},
      {p:'Glicose puxa água do intracelular e dilui o sódio', k:['puxa','desidrata','dilui','hiponatremia','sai da célula']},
      {p:'Distinguiu osmolaridade calculada de tonicidade nas fórmulas', k:['tonicidade','efetiva','fórmula','2 x','2×','18','6']}]}]};

EX['pequenos-grupos/acidose-metabolica-queda-do-ph-735-por-acumulo-de-acidos'] = {fontes:'acidobase',
 internet:[
  {t:'me', f:ADAPT, e:'Paciente com pH 7,28, PaCO₂ 30 mmHg e HCO₃⁻ 14 mEq/L apresenta:', a:['Acidose respiratória com compensação metabólica','Acidose metabólica com compensação respiratória','Alcalose metabólica descompensada','Distúrbio misto sem compensação'],
   ok:1, d:'Qual das duas variáveis anda no mesmo sentido do pH? Essa é a compensação; a outra é o distúrbio.', w:'pH 7,28 → acidemia. O HCO₃⁻ baixo (14) explica acidose → distúrbio primário <b>metabólico</b>. A PaCO₂ baixa (30) explicaria alcalose, logo é a <b>compensação respiratória</b>. Confira com Winter: 1,5 × 14 + 8 = 29 ± 2, bate com 30 — compensação adequada, sem distúrbio misto.'},
  {t:'me', f:ADAPT, e:'O principal sistema tampão do líquido extracelular é:', a:['Fosfato','Bicarbonato / ácido carbônico','Proteínas plasmáticas','Amônia'],
   ok:1, d:'Não é o de melhor pKa. É o único cujos dois componentes são regulados por órgãos diferentes.', w:'O par <b>HCO₃⁻/H₂CO₃</b> domina o LEC não por ter bom pKa (6,1 está longe de 7,4), mas por ser um <b>sistema aberto</b>: o CO₂ é ajustado pelo pulmão em minutos e o HCO₃⁻ pelo rim em dias, de forma independente. Fosfato e proteínas dominam o meio <i>intracelular</i>; a amônia atua na excreção renal de ácido, não no tamponamento plasmático.'},
  {t:'me', f:ADAPT, e:'Paciente com vômitos incoercíveis há três dias: pH 7,52, PaCO₂ 47 mmHg, HCO₃⁻ 36 mEq/L. O diagnóstico é:', a:['Alcalose respiratória compensada','Alcalose metabólica com compensação respiratória','Acidose metabólica','Distúrbio misto'],
   ok:1, d:'O que o vômito faz perder? E perder ácido equivale a quê?', w:'pH 7,52 → alcalemia. HCO₃⁻ alto (36) explica alcalose → primário <b>metabólico</b>. A PaCO₂ elevada (47) é a <b>compensação respiratória</b> por hipoventilação. Bate com a história: o vômito perde HCl gástrico, e perder ácido equivale a ganhar base. Note que essa compensação é limitada — hipoventilar demais causaria hipoxemia.'}],
 ia:[
  {t:'me', e:'Paciente com pH 7,30, PaCO₂ 28, HCO₃⁻ 13, Na 140, Cl 100. Qual o distúrbio e o ânion gap?', a:['Acidose metabólica com ânion gap normal','Acidose metabólica com ânion gap elevado (27) — adição de ácido','Acidose respiratória com AG 27','Alcalose respiratória compensada'],
   ok:1, d:'AG = Na − (Cl + HCO₃). O normal é 8–12.', w:'pH baixo com HCO₃⁻ baixo = acidose metabólica; a PaCO₂ de 28 é compensatória (Winter: 1,5×13+8 = 27,5 ± 2). AG = 140 − (100 + 13) = <b>27</b>, muito acima de 8–12 → <b>adição de ácido</b>: cetoacidose, acidose lática, uremia ou intoxicação. Se fosse perda de bicarbonato (diarreia), o cloro subiria para ocupar o lugar e o AG ficaria normal.'},
  {t:'me', e:'Um alpinista chega a 4.500 m. Que distúrbio ácido-base é esperado nas primeiras horas?', a:['Acidose metabólica por lactato','Alcalose respiratória pela hiperventilação secundária à hipoxemia','Acidose respiratória por hipoventilação','Alcalose metabólica'],
   ok:1, d:'O que a hipoxemia faz com a ventilação — e o que a ventilação faz com o CO₂?', w:'A PO₂ inspirada cai com a pressão barométrica; a hipoxemia estimula os quimiorreceptores <b>periféricos</b>, aumentando a ventilação. Hiperventilar elimina CO₂ → <b>alcalose respiratória</b>. Nos dias seguintes o rim compensa excretando bicarbonato, o que normaliza o pH e libera o drive ventilatório — parte central da aclimatação. A acetazolamida acelera esse processo forçando a bicarbonatúria.'},
  {t:'ab', e:'Descreva as três linhas de defesa do organismo contra uma carga ácida, indicando o tempo de ação e a capacidade de cada uma.',
   d:'Segundos, minutos, dias — e uma delas nunca resolve sozinha, só ganha tempo.',
   g:'<b>1ª linha — tampões químicos (segundos).</b> Agem imediatamente, mas apenas <i>escondem</i> o H⁺; não o eliminam do corpo. No LEC domina o par bicarbonato/ácido carbônico; no LIC, o fosfato e as proteínas (com destaque para a hemoglobina, que tampona o H⁺ gerado pela hidratação do CO₂ dentro da hemácia). Na acidose crônica o osso também participa, liberando carbonato de cálcio — o que explica a doença óssea da acidose tubular renal e da doença renal crônica.<br><br><b>2ª linha — compensação respiratória (minutos).</b> O H⁺ estimula os quimiorreceptores e a ventilação aumenta, eliminando CO₂ e, portanto, ácido volátil. É rápida e potente, mas <b>nunca normaliza o pH</b> — apenas o aproxima do normal, porque o próprio retorno do pH reduz o estímulo que a mantém. A regra de Winter (PaCO₂ esperada = 1,5 × HCO₃⁻ + 8 ± 2) mede se ela está adequada.<br><br><b>3ª linha — compensação renal (horas a dias).</b> É a única que realmente <b>elimina</b> ácido fixo e <b>regenera</b> bicarbonato. Faz isso por três vias: reabsorção de quase todo o HCO₃⁻ filtrado no túbulo proximal, excreção de acidez titulável (H⁺ tamponado por fosfato) e, sobretudo, excreção de <b>NH₄⁺</b> — o mecanismo de maior capacidade de adaptação, que pode aumentar várias vezes na acidose crônica. Lenta, porém definitiva.',
   c:[{p:'Tampões químicos agem em segundos e não eliminam o ácido', k:['tampão','tampões','segundos','bicarbonato','imediat']},
      {p:'Citou tampões intracelulares (fosfato, proteínas, hemoglobina) ou o osso', k:['fosfato','proteín','hemoglobina','osso','intracelular']},
      {p:'Compensação respiratória em minutos, eliminando CO₂', k:['respiratór','ventila','co2','co₂','minutos','pulmão','hiperventil']},
      {p:'Reconheceu que a compensação respiratória não normaliza o pH', k:['não normaliza','parcial','não corrige','aproxima','incompleta','nunca']},
      {p:'Compensação renal em horas a dias, com reabsorção de HCO₃⁻ e excreção de NH₄⁺', k:['renal','rim','dias','nh4','nh₄','amônio','acidez titulável','regenera']}]}]};

EX['pequenos-grupos/mecanismos-de-acao-hormonal-e-retroalimentacao--uc-1-sem'] = {fontes:'endocrino',
 internet:[
  {t:'me', f:ADAPT, e:'Hormônios lipossolúveis (esteroides e tireoidianos) atuam principalmente por meio de:', a:['Receptores de membrana acoplados à proteína G','Receptores intracelulares que modulam a transcrição gênica','Canais iônicos ligantes-dependentes','Receptores com atividade tirosina-quinase na membrana'],
   ok:1, d:'Se o hormônio atravessa a membrana, onde ele vai encontrar o receptor?', w:'Por serem lipossolúveis, atravessam a bicamada e se ligam a receptores <b>citoplasmáticos ou nucleares</b>. O complexo hormônio-receptor age como fator de transcrição, alterando a síntese de proteínas. Consequência prática: início de ação <b>lento</b> (horas) e efeito <b>prolongado</b> — o oposto dos hidrossolúveis, que agem em segundos por segundos mensageiros.'},
  {t:'me', f:ADAPT, e:'No eixo hipotálamo-hipófise-tireoide, o aumento de T3 e T4 circulantes provoca:', a:['Aumento da secreção de TRH e TSH','Inibição da secreção de TRH e TSH por retroalimentação negativa','Aumento apenas do TSH','Nenhum efeito sobre o hipotálamo'],
   ok:1, d:'O produto final quase sempre freia quem o mandou produzir.', w:'É o feedback negativo de <b>alça longa</b>: T3/T4 inibem tanto o hipotálamo (TRH) quanto a adeno-hipófise (TSH). É isso que torna o TSH o melhor exame de triagem da tireoide: no hipotireoidismo primário o TSH sobe (tentando estimular uma glândula que não responde), e no hipertireoidismo primário o TSH é suprimido.'},
  {t:'me', f:ADAPT, e:'Hormônios hidrossolúveis, como a adrenalina e os peptídicos, agem por:', a:['Difusão direta pela membrana até o núcleo','Receptores de membrana e sistemas de segundos mensageiros, como o AMPc','Ligação ao DNA sem intermediários','Transporte ativo para dentro do núcleo'],
   ok:1, d:'Se o hormônio não consegue entrar, ele precisa de um "recado" que percorra o caminho por dentro.', w:'Não atravessam a membrana, então se ligam a receptores <b>de superfície</b> e disparam cascatas de <b>segundos mensageiros</b> (AMPc, IP₃/DAG, Ca²⁺, GMPc). Isso gera duas propriedades: <b>rapidez</b> (segundos a minutos) e <b>amplificação</b> — uma molécula de hormônio ativa muitas proteínas G, que ativam muitas adenilato-ciclases, e assim por diante.'}],
 ia:[
  {t:'me', e:'Uma paciente usa corticoide oral em dose alta por 6 meses e o suspende abruptamente, evoluindo com hipotensão, fraqueza e hipoglicemia. A explicação é:', a:['Alergia ao medicamento','Supressão crônica do eixo hipotálamo-hipófise-adrenal por feedback negativo, com atrofia adrenal e incapacidade de produzir cortisol','Excesso de ACTH circulante','Hipertireoidismo secundário'],
   ok:1, d:'O corpo passou 6 meses recebendo cortisol de fora. O que ele fez com a própria fábrica?', w:'O corticoide exógeno mantém o feedback negativo ligado o tempo todo: o CRH e o ACTH ficam suprimidos e o córtex adrenal <b>atrofia</b>. Retirado o remédio de repente, não há cortisol exógeno nem endógeno — é a <b>insuficiência adrenal secundária</b>, potencialmente fatal. Por isso corticoide de uso prolongado se retira em <b>desmame lento</b>, dando tempo para o eixo se recuperar.'},
  {t:'me', e:'Por que um mesmo hormônio pode produzir efeitos opostos em tecidos diferentes?', a:['Porque a concentração do hormônio varia entre tecidos','Porque o efeito é determinado pelo tipo de receptor e pela via de sinalização presentes na célula-alvo, não pelo hormônio','Porque o hormônio muda de estrutura no sangue','Porque só um tecido tem receptor por vez'],
   ok:1, d:'O hormônio é a chave; quem decide o que acontece é a fechadura.', w:'Quem determina a resposta é a <b>célula-alvo</b>. A adrenalina é o exemplo clássico: em receptores <b>β₂</b> da musculatura esquelética causa vasodilatação; em receptores <b>α₁</b> da pele e do território esplâncnico causa vasoconstrição. Mesmo hormônio, mesma concentração, efeitos opostos — porque a via intracelular acoplada é diferente.'},
  {t:'ab', e:'Compare o mecanismo de ação dos hormônios lipossolúveis e hidrossolúveis, explicando por que essa diferença determina a velocidade e a duração dos efeitos.',
   d:'Comece pela pergunta física: o hormônio consegue ou não atravessar a bicamada lipídica?',
   g:'<b>Lipossolúveis</b> (esteroides — cortisol, aldosterona, testosterona, estrogênio — e tireoidianos): atravessam livremente a membrana plasmática e se ligam a <b>receptores intracelulares</b>, citoplasmáticos ou nucleares. O complexo hormônio-receptor liga-se a elementos responsivos no DNA e atua como <b>fator de transcrição</b>, alterando a síntese de proteínas específicas. Como o efeito depende de transcrever RNA e traduzir proteína, o início é <b>lento</b> (horas) e o efeito é <b>prolongado</b> (horas a dias), durando enquanto as proteínas produzidas persistirem. Circulam ligados a proteínas transportadoras, o que aumenta sua meia-vida.<br><br><b>Hidrossolúveis</b> (peptídicos — insulina, GH, ADH — e catecolaminas): não atravessam a membrana e se ligam a <b>receptores de superfície</b>, que ativam cascatas de <b>segundos mensageiros</b> (AMPc via proteína G, IP₃/DAG, Ca²⁺, ou tirosina-quinase no caso da insulina). Como agem sobre proteínas <b>já existentes</b> — fosforilando-as e mudando sua atividade —, o efeito começa em <b>segundos a minutos</b> e é <b>curto</b>. Circulam livres no plasma e têm meia-vida curta.<br><br>A cascata dos hidrossolúveis traz ainda uma vantagem própria: <b>amplificação</b> do sinal, já que cada etapa ativa muitas moléculas da etapa seguinte — o que permite resposta intensa a concentrações hormonais mínimas.',
   c:[{p:'Lipossolúveis atravessam a membrana e usam receptor intracelular/nuclear', k:['atravessa','intracelular','nuclear','citoplasm','lipossol']},
      {p:'Lipossolúveis agem pela transcrição gênica / síntese proteica', k:['transcri','gênic','dna','síntese','proteín','rna']},
      {p:'Hidrossolúveis usam receptor de membrana e segundos mensageiros', k:['membrana','segundo mensageiro','segundos mensageiros','ampc','amp cíclico','proteína g','superfície']},
      {p:'Relacionou lipossolúvel a efeito lento e duradouro', k:['lento','horas','prolongad','duradouro','demora']},
      {p:'Relacionou hidrossolúvel a efeito rápido e curto', k:['rápid','segundos','minutos','curt','breve']}]}]};

EX['pequenos-grupos/pequenos-grupos--grupo-2-2'] = {fontes:'endocrino',
 internet:[
  {t:'me', f:ADAPT, e:'A diferença fundamental entre glândulas endócrinas e exócrinas é que:', a:['As endócrinas produzem enzimas e as exócrinas produzem hormônios','As endócrinas não possuem ducto e lançam sua secreção na corrente sanguínea; as exócrinas possuem ducto','As endócrinas são maiores','As exócrinas atuam apenas na pele'],
   ok:1, d:'A palavra-chave está na presença ou ausência de um canal de saída.', w:'<b>Endócrinas</b> são glândulas <b>sem ducto</b>: secretam hormônios diretamente no interstício, de onde alcançam os capilares e a circulação. <b>Exócrinas</b> lançam a secreção por um <b>ducto</b>, para a superfície do corpo ou para a luz de um órgão. O pâncreas é o exemplo didático das duas coisas ao mesmo tempo: ilhotas endócrinas (insulina, glucagon) e ácinos exócrinos (enzimas digestivas pelo ducto pancreático).'},
  {t:'me', f:ADAPT, e:'A adeno-hipófise e a neuro-hipófise diferem porque:', a:['Ambas sintetizam os mesmos hormônios','A adeno-hipófise sintetiza seus próprios hormônios; a neuro-hipófise apenas armazena e libera ADH e ocitocina produzidos no hipotálamo','A neuro-hipófise produz o TSH','A adeno-hipófise é de origem neural'],
   ok:1, d:'Uma é uma fábrica, a outra é um depósito com terminações nervosas.', w:'A <b>adeno-hipófise</b> (origem epitelial, da bolsa de Rathke) é uma <b>fábrica</b>: produz TSH, ACTH, FSH, LH, GH e prolactina, sob comando dos fatores hipotalâmicos que chegam pelo sistema porta-hipofisário. A <b>neuro-hipófise</b> (origem neural) é um <b>depósito</b>: ADH e ocitocina são sintetizados nos núcleos supraóptico e paraventricular do hipotálamo e descem por axônios até serem liberados ali.'},
  {t:'me', f:ADAPT, e:'O hormônio antidiurético (ADH) é produzido no hipotálamo e tem como principal função:', a:['Aumentar a excreção de água pelos rins','Aumentar a reabsorção de água no ducto coletor, concentrando a urina','Reduzir a pressão arterial','Estimular a produção de insulina'],
   ok:1, d:'O nome já diz: <i>anti</i>-diurético.', w:'O ADH atua no receptor <b>V₂</b> do ducto coletor, inserindo <b>aquaporina-2</b> na membrana luminal e permitindo a reabsorção de água livre — urina menor em volume e mais concentrada. Em doses altas também é vasoconstritor (receptor V₁), daí o nome alternativo <b>vasopressina</b>. Sua falta causa diabetes insipidus, com poliúria de urina diluída.'}],
 ia:[
  {t:'me', e:'Uma paciente apresenta ganho de peso, intolerância ao frio, bradicardia, pele seca e constipação. O TSH está elevado e o T4 livre, baixo. O diagnóstico é:', a:['Hipertireoidismo primário','Hipotireoidismo primário','Hipotireoidismo secundário (hipofisário)','Doença de Graves'],
   ok:1, d:'TSH alto significa que a hipófise está gritando. Para quem ela grita, e por que a resposta não vem?', w:'TSH <b>alto</b> com T4 <b>baixo</b> localiza o problema na própria <b>tireoide</b>: ela não responde, e a hipófise, liberada do feedback negativo, aumenta o TSH tentando estimulá-la. Isso é hipotireoidismo <b>primário</b>. Se fosse <b>secundário</b>, o defeito estaria na hipófise e o TSH viria baixo ou inapropriadamente normal junto com o T4 baixo. Os sintomas são a lentificação metabólica generalizada.'},
  {t:'me', e:'Qual glândula é chamada de "maestro" do sistema endócrino e por quê?', a:['A tireoide, por controlar o metabolismo basal','A hipófise, por secretar hormônios tróficos que regulam outras glândulas — ainda que ela própria seja comandada pelo hipotálamo','A suprarrenal, por produzir cortisol','O pâncreas, por controlar a glicemia'],
   ok:1, d:'Quem manda em tireoide, suprarrenal e gônadas ao mesmo tempo?', w:'A <b>hipófise</b> comanda tireoide (TSH), córtex adrenal (ACTH) e gônadas (FSH e LH), além de GH e prolactina — daí o apelido. Vale a ressalva que a questão faz: o verdadeiro maestro é o <b>hipotálamo</b>, que comanda a hipófise por meio dos fatores liberadores e inibidores e integra o sistema endócrino ao nervoso.'},
  {t:'ab', e:'Descreva o eixo hipotálamo-hipófise-adrenal (HHA), desde o estímulo até o efeito, e explique como o feedback negativo o regula.',
   d:'Três andares, três hormônios, e uma seta que volta para os dois primeiros.',
   g:'<b>Estímulo:</b> estresse físico ou psíquico, hipoglicemia, e o ritmo circadiano (pico pela manhã, vale à noite).<br><br><b>Andar 1 — hipotálamo:</b> os núcleos paraventriculares liberam <b>CRH</b> (hormônio liberador de corticotrofina) no sistema porta-hipofisário.<br><br><b>Andar 2 — adeno-hipófise:</b> o CRH estimula os corticotrofos a secretar <b>ACTH</b>, que cai na circulação sistêmica.<br><br><b>Andar 3 — córtex da suprarrenal:</b> o ACTH age na <b>zona fasciculada</b>, estimulando a síntese e a liberação de <b>cortisol</b> (e, em menor grau, de androgênios na zona reticular).<br><br><b>Efeitos do cortisol:</b> aumento da glicemia por gliconeogênese, catabolismo proteico e lipólise, ação anti-inflamatória e imunossupressora, permissividade à ação das catecolaminas (manutenção do tônus vascular) e efeito mineralocorticoide leve.<br><br><b>Feedback negativo:</b> o cortisol circulante inibe tanto a liberação de CRH pelo hipotálamo quanto a de ACTH pela hipófise — é a <b>alça longa</b>. Existe ainda a <b>alça curta</b>, em que o próprio ACTH inibe o CRH. Esse circuito explica dois quadros clássicos: na <b>doença de Addison</b> (falência adrenal primária) o cortisol é baixo e o ACTH sobe muito, causando hiperpigmentação; no uso crônico de corticoide exógeno, o feedback fica permanentemente ligado, CRH e ACTH são suprimidos e a adrenal atrofia — daí a necessidade de desmame lento.',
   c:[{p:'Hipotálamo libera CRH', k:['crh','corticotrofina','hipotálamo']},
      {p:'Hipófise libera ACTH', k:['acth','adeno','hipófise','corticotrof']},
      {p:'Adrenal produz cortisol na zona fasciculada', k:['cortisol','suprarrenal','adrenal','fasciculada','córtex']},
      {p:'Citou pelo menos um efeito do cortisol', k:['glicem','gliconeogênese','anti-inflamat','imunossup','catabol','estresse']},
      {p:'Explicou o feedback negativo sobre hipotálamo e hipófise', k:['feedback','retroaliment','inibe','negativ']}]}]};

EX['pequenos-grupos/red-and-beige-modern-medical-professional-cardiovascular'] = {fontes:'cardio',
 internet:[
  {t:'me', f:ADAPT, e:'A sequência correta do sistema de condução elétrica do coração é:', a:['Nó AV → nó SA → feixe de His → Purkinje','Nó SA → vias internodais → nó AV → feixe de His → ramos → fibras de Purkinje','Feixe de His → nó SA → nó AV → Purkinje','Purkinje → nó AV → nó SA → feixe de His'],
   ok:1, d:'Comece pelo marca-passo natural, no átrio direito.', w:'O impulso nasce no <b>nó sinoatrial</b> (marca-passo fisiológico, ~70–80 bpm, no átrio direito junto à veia cava superior), percorre as vias internodais até o <b>nó atrioventricular</b> — onde sofre um <b>retardo</b> essencial, que dá tempo aos átrios de esvaziar antes da sístole ventricular —, desce pelo <b>feixe de His</b>, se divide nos ramos direito e esquerdo e se espalha pelas <b>fibras de Purkinje</b>, despolarizando os ventrículos de forma rápida e sincronizada.'},
  {t:'me', f:ADAPT, e:'A primeira bulha cardíaca (B1) corresponde ao fechamento de quais valvas?', a:['Aórtica e pulmonar','Mitral e tricúspide','Mitral e aórtica','Tricúspide e pulmonar'],
   ok:1, d:'B1 marca o começo da sístole. Quais valvas precisam fechar para o ventrículo poder pressurizar?', w:'<b>B1</b> = fechamento das valvas <b>atrioventriculares</b> (mitral e tricúspide), marcando o início da <b>sístole</b> ventricular. <b>B2</b> = fechamento das <b>semilunares</b> (aórtica e pulmonar), marcando o início da <b>diástole</b>. Mnemônico: B1 é o "TUM" e B2 é o "TÁ"; entre B1 e B2 está a sístole.'},
  {t:'me', f:ADAPT, e:'Sobre as camadas da parede arterial, é correto afirmar que a túnica média:', a:['É formada por endotélio simples pavimentoso','É rica em músculo liso e fibras elásticas, sendo a principal responsável pelo controle do calibre do vaso','É a camada mais externa, de tecido conjuntivo frouxo','Está ausente nas artérias elásticas'],
   ok:1, d:'Qual camada precisa se contrair para a arteríola mudar de diâmetro?', w:'A <b>túnica média</b> concentra o <b>músculo liso</b> e as fibras elásticas — é ela que determina vasoconstrição e vasodilatação e, portanto, a resistência vascular. A <b>íntima</b> é o endotélio mais uma fina camada subendotelial; a <b>adventícia</b> é o conjuntivo externo com vasa vasorum e nervos. Nas <b>arteríolas</b> a média é proporcionalmente muito espessa, o que faz delas os principais vasos de resistência.'}],
 ia:[
  {t:'me', e:'Por que o retardo do impulso no nó atrioventricular (cerca de 0,1 s) é fisiologicamente essencial?', a:['Para reduzir o gasto energético do coração','Para permitir que os átrios completem o esvaziamento antes de os ventrículos contraírem','Para diminuir a frequência cardíaca em repouso','Para proteger as valvas semilunares'],
   ok:1, d:'O que aconteceria com o enchimento ventricular se átrios e ventrículos contraíssem juntos?', w:'O nó AV conduz devagar de propósito. Esse atraso de ~0,1 s garante que a <b>sístole atrial termine antes de a ventricular começar</b>, completando o enchimento ventricular — o chamado "chute atrial", que contribui com 15–25% do volume diastólico final. É por isso que na fibrilação atrial, onde essa contração organizada se perde, o débito cardíaco cai, sobretudo em corações rígidos.'},
  {t:'me', e:'A pressão de pulso de 90 mmHg (PA 160/70) em um idoso indica mais provavelmente:', a:['Estenose aórtica grave','Redução da complacência da aorta por enrijecimento arterial','Choque hipovolêmico','Tamponamento cardíaco'],
   ok:1, d:'PP = PAS − PAD depende do volume sistólico e da elasticidade da aorta.', w:'Com o envelhecimento, elastina é substituída por colágeno na aorta. Uma aorta rígida amortece mal a ejeção: a sistólica sobe e, como o recuo elástico na diástole é menor, a diastólica cai — a <b>hipertensão sistólica isolada</b>, com PP alargada. As outras três alternativas cursam com PP <b>estreitada</b>, por baixo volume sistólico.'},
  {t:'ab', e:'Descreva as fases do ciclo cardíaco, relacionando cada uma ao estado das valvas, ao volume ventricular e às bulhas.',
   d:'São quatro fases se você agrupar; comece pela contração isovolumétrica e acompanhe a pressão dentro do ventrículo.',
   g:'<b>1. Contração isovolumétrica.</b> O ventrículo começa a contrair. A pressão intraventricular ultrapassa a atrial e as valvas <b>atrioventriculares se fecham</b> — é a <b>B1</b>. As semilunares ainda estão fechadas, então o volume não muda (daí "isovolumétrica"), só a pressão sobe. Volume = VDF ≈ 120 mL.<br><br><b>2. Ejeção.</b> Quando a pressão ventricular supera a aórtica (~80 mmHg à esquerda), a <b>valva aórtica abre</b> e o sangue é ejetado — rapidamente no início, depois mais lentamente. Sai o volume sistólico (~70 mL), restando o volume sistólico final (~50 mL).<br><br><b>3. Relaxamento isovolumétrico.</b> O ventrículo relaxa, a pressão cai abaixo da aórtica e as <b>valvas semilunares se fecham</b> — é a <b>B2</b>. As AV ainda estão fechadas: de novo o volume não muda enquanto a pressão despenca.<br><br><b>4. Enchimento.</b> Quando a pressão ventricular cai abaixo da atrial, as <b>valvas AV abrem</b>. Há um enchimento rápido inicial (passivo — se houver B3, é aqui), depois a diástase (fluxo lento) e, por fim, a <b>sístole atrial</b>, que acrescenta os últimos 15–25% do volume (se houver B4, é aqui). O ventrículo volta ao VDF e o ciclo recomeça.<br><br>Fração de ejeção = VS/VDF ≈ 70/120 ≈ 58% (normal 55–70%).',
   c:[{p:'Citou a contração isovolumétrica com fechamento das valvas AV e B1', k:['isovolum','b1','primeira bulha','atrioventricular','mitral']},
      {p:'Descreveu a ejeção com abertura das semilunares', k:['ejeç','semilunar','aórtica','abre','sístole']},
      {p:'Citou o relaxamento isovolumétrico e a B2', k:['relaxamento','b2','segunda bulha','fecham']},
      {p:'Descreveu o enchimento e a sístole atrial', k:['enchimento','diástole','sístole atrial','átrio','diástase']},
      {p:'Relacionou volumes: VDF, VS e VSF ou fração de ejeção', k:['vdf','vsf','volume sistólico','fração de ejeção','120','70']}]}]};

EX['pequenos-grupos/pequenos-grupos--grupo-2-1'] = {fontes:'semio',
 internet:[
  {t:'me', f:ADAPT, e:'Um manguito de largura inadequadamente estreita para a circunferência do braço resulta em:', a:['Subestimação da pressão arterial','Superestimação da pressão arterial','Nenhuma alteração','Impossibilidade de auscultar os sons'],
   ok:1, d:'Um manguito estreito precisa de mais pressão para ocluir a mesma artéria.', w:'O manguito estreito distribui a pressão por uma área pequena e precisa ser inflado <b>além</b> do necessário para ocluir a artéria — o aparelho registra valor <b>superestimado</b>. É a causa clássica de "pseudo-hipertensão" no paciente obeso. Regra: a bolsa deve cobrir ~80% da circunferência do braço e ter largura de ~40% dela. Manguito largo demais faz o contrário: subestima.'},
  {t:'me', f:ADAPT, e:'Na medida da pressão arterial, a pressão diastólica corresponde a qual fase de Korotkoff?', a:['Fase I — primeiro som audível','Fase III — som mais nítido','Fase V — desaparecimento dos sons','Fase II — sopro suave'],
   ok:2, d:'Abaixo da diastólica o fluxo volta a ser laminar. O que acontece com o som?', w:'A <b>fase I</b> (primeiro som) marca a <b>sistólica</b>; a <b>fase V</b> (desaparecimento) marca a <b>diastólica</b>. Entre elas o fluxo é turbulento e audível. A fase IV (abafamento) só é usada como PAD quando os sons persistem até zero — gestantes, crianças e estados hipercinéticos.'},
  {t:'me', f:ADAPT, e:'São considerados sinais vitais clássicos:', a:['Peso, altura, IMC e circunferência abdominal','Frequência cardíaca, frequência respiratória, temperatura e pressão arterial','Nível de consciência, marcha, fácies e decúbito','Hemoglobina, hematócrito, leucócitos e plaquetas'],
   ok:1, d:'São quatro medidas que qualquer paciente recebe na chegada.', w:'Os quatro clássicos são <b>FC, FR, temperatura e PA</b>. Muitos serviços incluem a dor como "quinto sinal vital" e a saturação de O₂ como "sexto". As outras alternativas trazem, respectivamente, medidas antropométricas, achados da inspeção geral e exames laboratoriais.'}],
 ia:[
  {t:'me', e:'Por que o tempo de enchimento capilar prolongado (> 3 s) é sinal precoce de choque?', a:['Porque indica desidratação da pele','Porque a vasoconstrição periférica é uma das primeiras compensações simpáticas, sacrificando a pele para preservar cérebro e coração','Porque reflete diretamente a queda da PA','Porque a temperatura ambiente altera o retorno capilar'],
   ok:1, d:'Na centralização da circulação, qual território o corpo desliga primeiro?', w:'A pele e o leito esplâncnico são os primeiros a serem "desligados" pela vasoconstrição simpática — isso acontece <b>antes</b> de a PA cair, ainda na fase compensada. A lição prática: pressão arterial normal <b>não exclui</b> choque; perfusão periférica, lactato e diurese são marcadores mais precoces.'},
  {t:'me', e:'Um paciente tem pulso radial presente, mas pulso pedioso ausente e extremidades frias, com PA 100/80 mmHg. O que a pressão de pulso estreitada sugere?', a:['Insuficiência aórtica','Baixo volume sistólico com vasoconstrição compensatória — típico de choque hipovolêmico ou cardiogênico','Hipertensão sistólica isolada','Febre'],
   ok:1, d:'PP = 100 − 80 = 20 mmHg. O normal é 30–50. O que faz esse número encolher?', w:'PP estreitada (20 mmHg) indica <b>volume sistólico reduzido</b> somado a vasoconstrição, que sustenta a diastólica. É o padrão do choque hipovolêmico e do cardiogênico, e combina com extremidades frias e perda dos pulsos distais. A insuficiência aórtica faria o oposto — PP alargada, com pulso amplo e "em martelo d\'água".'},
  {t:'ab', e:'Descreva a técnica correta de aferição da pressão arterial, apontando pelo menos quatro erros que levam a medidas falsas.',
   d:'Pense em quatro momentos: preparo do paciente, escolha do manguito, posição do braço e velocidade de desinsuflação.',
   g:'<b>Preparo:</b> repouso de 3 a 5 minutos, sentado, com as costas apoiadas, pernas descruzadas e pés no chão; bexiga vazia; sem fumar, tomar café ou fazer exercício nos 30 minutos anteriores; sem conversar durante a medida.<br><br><b>Manguito:</b> a bolsa inflável deve ter largura de ~40% da circunferência do braço e comprimento suficiente para envolver ~80% dela. Posicionar a borda inferior 2–3 cm acima da fossa cubital, sobre a artéria braquial.<br><br><b>Posição:</b> braço apoiado, na altura do <b>coração</b> (4º espaço intercostal).<br><br><b>Execução:</b> estimar a sistólica primeiro pelo <b>método palpatório</b> (palpando o pulso radial), inflar 20–30 mmHg acima desse valor, e desinsuflar a <b>2–3 mmHg por segundo</b>. Fase I de Korotkoff = PAS; fase V = PAD. Medir nos dois braços na primeira avaliação e adotar o de maior valor.<br><br><b>Erros que falseiam a medida:</b><br>1. <b>Manguito estreito</b> para o braço → superestima a PA (e manguito largo demais → subestima).<br>2. <b>Braço abaixo do nível do coração</b> → superestima (acima → subestima).<br>3. <b>Desinsuflação rápida</b> → subestima a sistólica e superestima a diastólica.<br>4. <b>Não usar o método palpatório</b> → risco de cair no <b>hiato auscultatório</b> e subestimar a sistólica.<br>5. Paciente falando, com bexiga cheia, sem repouso ou com o braço não apoiado → eleva falsamente a PA.',
   c:[{p:'Repouso prévio e paciente sentado com pés apoiados, sem falar', k:['repouso','sentad','3 a 5','pés','falar','cinco minutos']},
      {p:'Manguito de tamanho adequado (40% da largura / 80% da circunferência)', k:['manguito','40%','80%','largura','circunferência','tamanho']},
      {p:'Braço na altura do coração', k:['altura do coração','nível do coração','apoiado']},
      {p:'Desinsuflação de 2 a 3 mmHg por segundo', k:['2 a 3','2-3','dois a três','por segundo','lentamente','devagar']},
      {p:'Método palpatório e/ou hiato auscultatório', k:['palpatóri','hiato','radial','estimar']},
      {p:'Citou fase I como PAS e fase V como PAD', k:['fase i','fase 1','fase v','fase 5','korotkoff','primeiro som','desapareci']}]}]};

EX['pequenos-grupos/pequenos-grupos--grupo-2'] = {fontes:'respiratorio',
 internet:[
  {t:'me', f:ADAPT, e:'A cianose central torna-se perceptível quando a hemoglobina reduzida no sangue capilar ultrapassa aproximadamente:', a:['2 g/dL','5 g/dL','10 g/dL','15 g/dL'],
   ok:1, d:'É um valor <b>absoluto</b> de hemoglobina, não uma porcentagem.', w:'O limiar clássico é <b>5 g/dL de hemoglobina reduzida</b> — valor absoluto. Consequências: o <b>policitêmico</b> fica cianótico com hipoxemia leve (tem Hb de sobra para "sobrar" 5 g/dL reduzida), e o <b>anêmico grave</b> pode estar profundamente hipoxêmico sem cianose alguma.'},
  {t:'me', f:ADAPT, e:'A respiração de Kussmaul — ampla, profunda e regular — é típica de:', a:['Insuficiência cardíaca','Acidose metabólica, como na cetoacidose diabética','Lesão bulbar','Crise de ansiedade'],
   ok:1, d:'É uma compensação, não uma doença respiratória.', w:'Kussmaul é a <b>compensação respiratória da acidose metabólica</b>: o H⁺ estimula os quimiorreceptores, a ventilação alveolar aumenta, o CO₂ cai e o pH sobe. O padrão da insuficiência cardíaca e das lesões do SNC é o de <b>Cheyne-Stokes</b> (crescendo-decrescendo com apneia); o de lesão bulbar grave é o de <b>Biot</b> (caótico).'},
  {t:'me', f:ADAPT, e:'Urina espumosa persistente, edema periorbitário matinal e hipertensão sugerem:', a:['Infecção urinária baixa','Proteinúria significativa, indicando lesão glomerular','Desidratação','Litíase renal'],
   ok:1, d:'O que faz a urina espumar como sabão?', w:'A <b>proteinúria</b> reduz a tensão superficial da urina e faz espuma persistente. Somada a <b>edema</b> (pela queda da pressão oncótica plasmática) e <b>hipertensão</b>, aponta para <b>lesão glomerular</b> — a barreira de filtração deixando passar albumina. O edema da síndrome nefrótica é tipicamente <b>periorbitário e matinal</b>, porque à noite o decúbito redistribui o líquido para a face.'}],
 ia:[
  {t:'me', e:'Paciente com dispneia, taquipneia de 32 irpm, saturação de 88% em ar ambiente e uso de musculatura acessória. Qual achado indica maior gravidade imediata?', a:['A taquipneia isolada','A saturação de 88%, que na curva da hemoglobina já está na porção íngreme — pequenas quedas adicionais de PaO₂ derrubam muito a saturação','O uso de musculatura acessória apenas','A ausência de febre'],
   ok:1, d:'Lembre da forma em S da curva de dissociação da hemoglobina. Onde fica o "penhasco"?', w:'Saturação de 88% corresponde a PaO₂ de ~55–60 mmHg — exatamente o <b>joelho</b> da curva. Acima disso o platô protege (cair de 100 para 60 mmHg custa só ~8% de saturação); abaixo, a curva <b>despenca</b> e cada mmHg perdido custa caro. Por isso 60 mmHg / 90% é o limiar clássico de alarme. Os outros achados são importantes, mas é esse número que define a urgência.'},
  {t:'me', e:'Icterícia é clinicamente detectável em escleras a partir de qual nível de bilirrubina total?', a:['0,5 mg/dL','1,2 mg/dL','2 a 3 mg/dL','8 mg/dL'],
   ok:2, d:'O normal vai até ~1,2. É preciso mais que o dobro para o olho perceber.', w:'A bilirrubina total normal vai até ~1,2 mg/dL; a icterícia começa a ser visível nas <b>escleras</b> a partir de <b>2–3 mg/dL</b> e na pele a partir de ~4–5. A esclera aparece primeiro por ser rica em elastina, que tem alta afinidade pela bilirrubina. Avaliar sempre em <b>luz natural</b> — a luz artificial amarelada esconde e a fluorescente falseia.'},
  {t:'ab', e:'Relacione três sinais clínicos de alteração renal com o mecanismo fisiopatológico que os produz.',
   d:'Para cada sinal, pergunte: qual função renal falhou — filtrar, reabsorver, excretar ou secretar hormônio?',
   g:'<b>1. Edema.</b> Pode nascer de dois mecanismos. Na <b>síndrome nefrótica</b>, a lesão da barreira glomerular deixa passar albumina; a hipoalbuminemia reduz a pressão oncótica do plasma e o líquido escapa para o interstício — edema mole, frio, com cacifo, tipicamente periorbitário pela manhã. Na <b>síndrome nefrítica</b> e na insuficiência renal, a queda da filtração glomerular causa <b>retenção de sódio e água</b>, expandindo o volume extracelular.<br><br><b>2. Oligúria (< 400 mL/dia).</b> Reflete queda da taxa de filtração glomerular, seja por hipoperfusão renal (pré-renal — hipovolemia, choque), por lesão do próprio parênquima (renal — necrose tubular aguda, glomerulonefrite) ou por obstrução ao fluxo urinário (pós-renal). Como o rim é quem elimina os produtos nitrogenados, a oligúria costuma vir acompanhada de elevação de ureia e creatinina.<br><br><b>3. Hipertensão arterial.</b> Dois mecanismos se somam: a retenção de sódio e água expande o volume extracelular e aumenta o débito cardíaco; e a hipoperfusão renal ativa o <b>SRAA</b>, elevando a resistência vascular periférica pela angiotensina II e retendo mais sódio pela aldosterona.<br><br><b>Outros aceitáveis:</b> urina espumosa (proteinúria reduzindo a tensão superficial); anemia (queda da produção de <b>eritropoetina</b> pelo rim); doença óssea e hipocalcemia (falha na 1α-hidroxilação da vitamina D); prurido e hálito urêmico (retenção de toxinas nitrogenadas).',
   c:[{p:'Citou edema e o relacionou a proteinúria/hipoalbuminemia ou retenção de sódio', k:['edema','albumin','proteinúria','oncótica','retenção']},
      {p:'Citou oligúria ou alteração do volume urinário relacionada à queda da filtração', k:['oligúria','anúria','filtração','tfg','diurese','creatinina']},
      {p:'Citou hipertensão e a relacionou a volume e/ou SRAA', k:['hipertens','pressão','sraa','renina','angiotensina','volume']},
      {p:'Explicou o mecanismo, não apenas listou os sinais', k:['porque','devido','mecanismo','causa','leva a','resulta']}]}]};

EX['pequenos-grupos/uc-4-260908-172832'] = {fontes:'homeostase',
 internet:[
  {t:'me', f:ADAPT, e:'Durante o exercício físico intenso, a pressão arterial diastólica em um indivíduo saudável tende a:', a:['Aumentar proporcionalmente à sistólica','Manter-se estável ou cair discretamente, pela vasodilatação da musculatura ativa','Aumentar muito mais que a sistólica','Cair abaixo de 40 mmHg'],
   ok:1, d:'PAD depende sobretudo da resistência periférica. O que o músculo em atividade faz com ela?', w:'O simpático dispara, mas os metabólitos locais (adenosina, K⁺, CO₂, H⁺) produzem vasodilatação muscular tão extensa que a <b>RVP total cai</b>. Como a PAS depende do volume sistólico e a PAD da resistência, o resultado é sistólica bem alta com diastólica estável ou levemente reduzida. Diastólica que <i>sobe</i> no esforço é achado anormal.'},
  {t:'me', f:ADAPT, e:'O mecanismo com "ganho infinito" no controle da pressão arterial a longo prazo é:', a:['Barorreflexo carotídeo','Quimiorreflexo periférico','Mecanismo renal de líquidos corporais (natriurese pressórica)','Reflexo de Bainbridge'],
   ok:2, d:'Qual deles não se acomoda a um erro residual e continua agindo até zerar o desvio?', w:'Ganho infinito significa que o sistema <b>não aceita erro residual</b>: enquanto a PA estiver acima do ponto de equilíbrio, o rim continua excretando sódio e água, reduzindo volume, retorno venoso e débito — e só para quando a PA voltar ao ponto de partida. Todos os reflexos nervosos se acomodam a um erro residual e ainda se readaptam com o tempo.'},
  {t:'me', f:ADAPT, e:'A relação ventilação/perfusão (V/Q) ideal no pulmão como um todo é aproximadamente:', a:['0,2','0,8','1,5','3,0'],
   ok:1, d:'Divida a ventilação alveolar (~4,2 L/min) pelo débito cardíaco (~5 L/min).', w:'V/Q global ≈ <b>0,8</b> (4,2 L/min de ventilação alveolar para ~5 L/min de fluxo pulmonar). No pulmão de pé há gradiente: <b>ápice ~3</b> (mais próximo do espaço morto) e <b>base ~0,6</b> (mais próximo do shunt), porque a gravidade reduz mais a perfusão do que a ventilação no topo.'}],
 ia:[
  {t:'me', e:'Uma pessoa levanta-se rapidamente da cama e sente tontura passageira. Qual mecanismo falhou momentaneamente?', a:['O feedback positivo da coagulação','O barorreflexo, que não compensou a tempo a queda do retorno venoso','A termorregulação hipotalâmica','O reflexo de Hering-Breuer'],
   ok:1, d:'Ao ficar de pé, ~500 mL de sangue ficam represados nas pernas. Quem deveria corrigir isso em segundos?', w:'É a <b>hipotensão ortostática</b> transitória. Ao ficar de pé, a gravidade represa sangue nos membros inferiores, o retorno venoso cai e com ele o débito e a PA. O <b>barorreflexo</b> deveria corrigir em 1–2 segundos com taquicardia e vasoconstrição; quando esse ajuste atrasa, a perfusão cerebral cai brevemente e surge a tontura. É mais comum em idosos, desidratados e usuários de anti-hipertensivos.'},
  {t:'me', e:'Por que a hipoxemia da hipoventilação corrige facilmente com O₂ suplementar, mas a do shunt não?', a:['Porque no shunt não existe hipoxemia real','Porque no shunt o sangue não entra em contato com gás alveolar nenhum, então aumentar a FiO₂ dos alvéolos ventilados não o alcança','Porque a hipoventilação não altera a PaO₂','Porque o O₂ suplementar piora a hipoventilação'],
   ok:1, d:'Pergunte onde o oxigênio suplementar consegue chegar em cada caso.', w:'Na <b>hipoventilação</b>, os alvéolos são ventilados — só que de menos; enriquecer o ar inspirado eleva a PAO₂ e resolve a hipoxemia (embora não resolva a hipercapnia). No <b>shunt verdadeiro</b>, o sangue passa por alvéolos colapsados ou consolidados e <b>não toca gás nenhum</b>: por mais que se aumente a FiO₂ nos alvéolos abertos, esse sangue continua chegando dessaturado. Hipoxemia refratária ao O₂ é a assinatura do shunt.'},
  {t:'ab', e:'Explique como os sistemas nervoso, endócrino, cardiovascular, respiratório e renal se integram durante uma corrida de 30 minutos.',
   d:'Siga a demanda: o músculo precisa de mais O₂ e glicose, e produz mais CO₂, H⁺ e calor. Quem responde a cada uma dessas quatro coisas?',
   g:'<b>Sistema nervoso.</b> Antes mesmo da largada, o comando central (feedforward) já eleva a frequência cardíaca e a ventilação. Durante o esforço, o simpático aumenta FC, contratilidade e tônus venoso, enquanto o vagal se retira. Os quimiorreceptores e os mecanorreceptores musculares alimentam o ajuste contínuo.<br><br><b>Sistema cardiovascular.</b> O débito cardíaco pode subir de 5 para mais de 20 L/min, por aumento da FC e do volume sistólico (Frank-Starling, pelo maior retorno venoso da bomba muscular, somado ao inotropismo simpático). Há <b>redistribuição de fluxo</b>: vasodilatação metabólica no músculo ativo e no coração, vasoconstrição na pele (inicialmente), no rim e no território esplâncnico. A PAS sobe e a PAD se mantém ou cai, porque a RVP global diminui.<br><br><b>Sistema respiratório.</b> A ventilação-minuto sobe de ~6 para 100 L/min ou mais, por aumento do volume corrente e da frequência. Isso mantém a PaO₂ e elimina o CO₂ extra. A curva da hemoglobina se desvia à <b>direita</b> no músculo (efeito Bohr: ↑CO₂, ↑H⁺, ↑temperatura, ↑2,3-BPG), liberando mais O₂ justamente onde ele é consumido.<br><br><b>Sistema endócrino.</b> Adrenalina e noradrenalina reforçam a resposta cardiovascular e mobilizam substrato; glucagon e cortisol aumentam a glicogenólise e a gliconeogênese, enquanto a insulina cai — mantendo a glicemia apesar do consumo. ADH e aldosterona sobem, preservando volume diante da perda por suor.<br><br><b>Sistema renal e termorregulação.</b> O fluxo renal cai e o rim retém sódio e água. O calor produzido é dissipado por <b>vasodilatação cutânea e sudorese</b> — que competem com o músculo por fluxo sanguíneo e causam perda de água e eletrólitos. Se a corrida se prolongar em ambiente quente, essa competição é o que limita o desempenho e pode levar à exaustão pelo calor.',
   c:[{p:'Sistema nervoso: comando simpático e retirada vagal', k:['simpático','vagal','parassimpático','nervoso','comando central']},
      {p:'Cardiovascular: aumento do débito por FC e volume sistólico, com redistribuição de fluxo', k:['débito','frequência cardíaca','volume sistólico','redistribu','vasodilat','frank']},
      {p:'Respiratório: aumento da ventilação e efeito Bohr', k:['ventila','respirat','bohr','direita','volume corrente','co2','co₂']},
      {p:'Endócrino: catecolaminas, glucagon/cortisol e queda da insulina', k:['adrenalina','catecolamina','glucagon','cortisol','insulina','hormôn']},
      {p:'Renal e/ou termorregulação: retenção de água, sudorese, dissipação de calor', k:['renal','rim','suor','sudorese','temperatura','calor','adh','aldosterona']}]}]};
</script>
